filecoin-project/boost

- db/db.go
- go.mod
- go.sum
- gql.go
- gql/cors.go
- gql/graphiql.go
- gql/resolver.go
- gql/schema.graphql
- gql/server.go
```
go run gql.go
```
Open http://localhost:8080
> Add graphql server

- react/.gitignore
- react/src/App.js
- react/src/gql.js
- react/src/hooks.js
- react/src/index.css
Depends on https://github.com/filecoin-project/boost/pull/22
> Add react subscriptions / mutations

- README.md
- db/db_test.go
- db/fielddef.go
- storagemarket/deal_acceptance.go
- storagemarket/deal_execution.go
- storagemarket/provider.go
This PR is fixing a bug with a value used in goroutine, but not captured, as well as fixing a few linter issues.
> fix loop closure

- gql/resolver.go
- node/builder.go
- node/config/def.go
- node/config/types.go
- node/modules/storageminer.go
- storagemarket/adapter.go
- storagemarket/datatransfer/mock.go
- storagemarket/deal_execution.go
- storagemarket/deal_handlers.go
- storagemarket/deal_publisher.go
- storagemarket/provider.go
Implement publish deals part of deal execution
> Publish deal

- db/db.go
- db/db_test.go
- db/fielddef.go
- gql/resolver.go
- gql/schema.graphql
- node/builder.go
- node/config/def.go
- node/config/types.go
- node/modules/storageminer.go
- react/src/App.js
- react/src/gql.js
- react/src/hooks.js
- react/src/index.css
- storagemarket/adapter.go
- storagemarket/datatransfer/mock.go
- storagemarket/deal_execution.go
- storagemarket/deal_handlers.go
- storagemarket/deal_publisher.go
- storagemarket/provider.go
https://user-images.githubusercontent.com/169124/141477168-7103d6f7-bd0c-4140-8d17-dc629be9fbe3.mov
> deals page pagination

- gql/resolver.go
- gql/schema.graphql
- react/src/App.js
- react/src/gql.js
- react/src/index.css
> Stub out funds management page

- .github/workflows/label-syncer.yml
Ensures that labels are always synced with the labels.yml file and that it is the source of truth.
> chore: add labels sync action yml

- gql/resolver.go
- gql/resolver_dealpublish.go
- gql/schema.graphql
- gql/server.go
- node/modules/storageminer.go
- react/src/App.js
- react/src/DealDetail.js
- react/src/DealPublish.js
- react/src/gql.js
- react/src/index.css
- react/src/util.js
- storagemarket/deal_execution.go
- storagemarket/deal_publisher.go
> ux: deal publish

- gql/resolver.go
- gql/resolver_dealpublish.go
- gql/resolver_funds.go
- gql/schema.graphql
- gql/server.go
- node/modules/storageminer.go
- react/src/App.js
- react/src/Chart.js
- react/src/DealDetail.js
- react/src/DealPublish.js
- react/src/Funds.js
- react/src/gql.js
- react/src/index.css
- react/src/util.js
- storagemarket/deal_execution.go
- storagemarket/deal_publisher.go
> Stub out funds manager logs

- .circleci/config.yml
- itests/dummydeal_test.go
This PR is adding `boost` integration tests as part of CI.
> enable go test in CI

- storagemarket/deal_acceptance.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
- Adding some more logging.
- Added some TODOs.
- Moved the provider event loop logic to it's own file.
> Boost SM Refactor: #1

- cmd/boost/init.go
- fundmanager/fundmanager.go
- fundmanager/fundmanager_test.go
- gql/resolver_funds.go
- gql/schema.graphql
- node/builder.go
- node/config/types.go
- react/src/Chart.js
- react/src/DealPublish.js
- react/src/Funds.js
- react/src/StorageSpace.js
- react/src/gql.js
- react/src/index.css
- react/src/util.js
Replaces https://github.com/filecoin-project/boost/pull/82 to avoid merge conflicts
> add fund manager ux with escrow top-up

- db/create.sql
- db/fielddef.go
- db/funds.go
- fundmanager/fundmanager.go
- gql/resolver_funds.go
- react/src/Chart.js
- react/src/Funds.js
- react/src/index.css
- react/src/util.js
> Funds logs

- gql/dummy.go
- gql/dummy_test.go
So that deals stay in a the transferring state a little longer
> Serve dummy deal data slowly

- gql/resolver.go
- gql/schema.graphql
- react/src/App.js
- react/src/Funds.js
- react/src/StorageSpace.js
- react/src/gql.js
- react/src/index.css
> ux - storage space redux

- gql/dummy.go
- gql/resolver.go
- gql/resolver_transfers.go
- gql/schema.graphql
- react/package-lock.json
- react/package.json
- react/src/App.js
- react/src/DealTransfers.js
- react/src/Funds.js
- react/src/gql.js
- react/src/util.js
- storagemarket/deal_execution.go
- storagemarket/provider.go
- storagemarket/transfers.go
https://user-images.githubusercontent.com/169124/144250499-eb2f04d6-aae4-43a4-98e5-a8fe2f9d4d19.mov
> UX: transfers page

- gql/resolver.go
- gql/resolver_mpool.go
- gql/schema.graphql
- node/modules/storageminer.go
- react/src/App.js
- react/src/Mpool.css
- react/src/Mpool.js
- react/src/StorageSpace.js
- react/src/gql.js
- react/src/index.css
Just mocks out the mpool messages for now, although the code is in place (but commented out) for fetching local pending messages from lotus.
> Basic mpool introspection

- fundmanager/fundmanager.go
- gql/resolver_funds.go
- gql/schema.graphql
- react/package-lock.json
- react/package.json
- react/src/Funds.js
- react/src/gql.js
- react/src/index.css
> fund manager redesign

- storagemarket/provider.go
- storagemarket/provider_loop.go
We will revisit this later as part of the deal resumption issue. Don't need it for now.
> Remove restart code

- cmd/boost/dummydeal.go
- policy/policy.go
- policy/policy_debug.go
MaxProviderCollaral should be different depending on whether we run devnet or on mainnet.
> set chain-dependent max provider collateral

- gql/resolver.go
- gql/resolver_funds.go
- gql/resolver_mpool.go
- gql/resolver_storage.go
- gql/resolver_transfers.go
- gql/schema.graphql
- gql/types/bigint.go
- gql/types/bigint_test.go
- gql/types/uint64.go
- gql/types/uint64_test.go
- react/src/DealDetail.js
- react/src/DealTransfers.js
- react/src/Deals.js
- react/src/Funds.js
- react/src/StorageSpace.css
- react/src/StorageSpace.js
- react/src/gql.js
- react/src/hooks.js
- react/src/util.js
Depends on https://github.com/filecoin-project/boost/pull/117
> add graphql BigInt type and use BigInt in JS

- react/src/StorageSpace.js
Fixes https://github.com/filecoin-project/boost/issues/144
> update storage page state every second

- react/src/DealTransfers.js
> set minimum on data transfer graph to zero

- go.mod
- storagemarket/deal_execution.go
- storagemarket/deal_handler.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
- transport/httptransport/http_transport_test.go
Closes #126 .
Closes #112 .
Closes #162 .
> Deal resumption and funds untagging after publish

- go.mod
- transport/httptransport/http_transport.go
- transport/httptransport/http_transport_test.go
Resume http transfers post disconnect.
> Implement http tansfer resumption

- storagemarket/deal_execution.go
- storagemarket/provider_loop.go
Fixes https://github.com/filecoin-project/boost/issues/172
> fix: on restart deals in sealing state fail

- react/package-lock.json
- react/package.json
- react/src/App.js
- react/src/Components.js
- react/src/DealPublish.js
- react/src/DealTransfers.js
- react/src/Deals.js
- react/src/Funds.js
- react/src/Mpool.js
- react/src/SealingPipeline.js
- react/src/StorageSpace.js
- react/src/index.css
Fixes https://github.com/filecoin-project/boost/issues/122
> Anchor urls on each page

- db/deals.go
- go.mod
- gql/resolver.go
- gql/resolver_sealingpipeline.go
- gql/schema.graphql
- node/builder.go
- node/config/doc_gen.go
- node/impl/boost.go
- node/modules/storageminer.go
- node/modules/storageminer_svc.go
- react/package-lock.json
- react/package.json
- react/src/App.js
- react/src/Components.js
- react/src/DealPublish.js
- react/src/DealTransfers.js
- react/src/Deals.js
- react/src/Funds.js
- react/src/Mpool.js
- react/src/SealingPipeline.css
- react/src/SealingPipeline.js
- react/src/StorageSpace.js
- react/src/gql.js
- react/src/index.css
- sealingpipeline/sealingpipeline.go
- storagemarket/provider.go
- transport/httptransport/http_transport.go
- transport/httptransport/http_transport_test.go
Fixes: https://github.com/filecoin-project/boost/issues/163
> initial api for sealing pipeline state

- gql/resolver.go
- gql/schema.graphql
- react/src/App.js
- react/src/DealPublish.js
- react/src/DealTransfers.js
- react/src/Deals.js
- react/src/Funds.js
- react/src/SealingPipeline.js
- react/src/StorageSpace.js
- react/src/gql.js
- react/src/index.css
- react/src/util.js
> show updates in real time in menu

- gql/resolver.go
- storagemarket/deal_execution.go
- storagemarket/deal_handler.go
- storagemarket/deal_handler_test.go
- storagemarket/provider.go
- storagemarket/provider_test.go
- storagemarket/provider_transfer_test.go
- storagemarket/smtestutil/mocks.go
- transport/httptransport/http_transport.go
- Adds tests for deal transfer cancellation 
- Tests for failure handling and cleanup at each checkpoint
> Tests for failure and cancellation

- storagemarket/deal_execution.go
All context cancellation errors should be marked as recoverable.
> Dont fail deal on graceful shutdown of Boost

- cmd/boost/main.go
- db/funds.go
- db/funds_test.go
- fundmanager/fundmanager.go
- fundmanager/fundmanager_test.go
- go.mod
- gql/schema.graphql
- react/src/DealDetail.css
- react/src/DealDetail.js
- react/src/gql.js
- react/src/transform.js
- storagemarket/deal_execution.go
- storagemarket/logs/log.go
- storagemarket/lp2pimpl/net.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
- storagemarket/provider_test.go
- storagemarket/types/types.go
- storagemarket/types/types_cbor_gen.go
- transport/httptransport/http_transport.go
- transport/httptransport/http_transport_test.go
- transport/httptransport/libp2p_server.go
- transport/types/types.go
* feat: update to lotus master
* feat: show deal log params
* fix: log level output
* fix: log params output
* fix: date parsing
* fix: convert deal log errors to string
* Fix testing errors (#236)
* fix errors
* Update storagemarket/provider.go
Co-authored-by: dirkmc <dirkmdev@gmail.com>
Co-authored-by: dirkmc <dirkmdev@gmail.com>
* feat: expandable log params
* Fixes based on integration testing (#238)
* fixes for testing
* debug flaky test
* address review
* fix failing test
* use the correct transfer progress code
* feat: add ID to TransferState
* feat: improve logging
Co-authored-by: Aarsh Shah <aarshkshah1992@gmail.com>
> update to lotus master (#234)

- react/src/DealDetail.css
- react/src/DealDetail.js
https://user-images.githubusercontent.com/169124/155109034-edcd097a-0dec-424c-8ace-e24bc54968be.mov
> copy deal uuid to clipboard

- gql/resolver_epoch.go
- gql/schema.graphql
- react/src/App.css
- react/src/App.js
- react/src/Epoch.css
- react/src/Epoch.js
- react/src/gql.js
Add an indicator showing the current chain height in the top right corner of the UI:
> show chain height in UI

- gql/resolver.go
- gql/resolver_legacy.go
- gql/schema.graphql
- node/modules/storageminer.go
- react/src/App.js
- react/src/Deals.js
- react/src/LegacyDealDetail.js
- react/src/LegacyDeals.css
- react/src/LegacyDeals.js
- react/src/gql.js
> Legacy deals ux

- gql/resolver_ask.go
- gql/resolver_libp2p.go
- gql/schema.graphql
- react/src/App.js
- react/src/Menu.js
- react/src/Settings.css
- react/src/Settings.js
- react/src/gql.js
> Settings page

- gql/resolver_ask.go
- gql/schema.graphql
- react/src/Settings.css
- react/src/Settings.js
- react/src/gql.js
https://user-images.githubusercontent.com/169124/155496875-c64892a9-abf3-4604-aa8b-e97fa6d759f4.mov
> Set storage ask

- gql/resolver_epoch.go
- gql/schema.graphql
- react/src/DealDetail.js
- react/src/Epoch.js
- react/src/gql.js
> Show current epoch on deal detail page

- go.mod
- itests/dummydeal_test.go
- itests/main_test.go
- itests/markets_v1_deal_test.go
- itests/test_framework.go
This PR is extracting the devnet setup into `TestMain` and then every integration tests starts off with a devnet + Boost already instantiated.
> extract devnet into TestMain

- gql/server.go
So that if you're looking at eg "http://server/legacy-storage-deals" and you refresh the page, it will serve the react app and navigate to the correct page (instead of a 404)
> Serve relative paths from react app

- client/deal.go
- itests/test_framework.go
- node/modules/storageminer.go
- storagemarket/lp2pimpl/net.go
- storagemarket/types/deal_state.go
- storagemarket/types/types.go
- storagemarket/types/types_cbor_gen.go
- Add a signature to the deal status request and check the signature
- Add several fields to the deal status response to match deal status v1 protocol
> Add fields to deal status response

- react/src/Deals.css
- react/src/Deals.js
- react/src/LegacyDeals.js
- Scroll to top when changing page
- Add "first page" link in pagination bar
- Poll every 5 seconds for changes to legacy deals
> Pagination UX improvements

- api/api.go
- api/proxy_gen.go
- cmd/boost/legacy_deals.go
- cmd/boost/main.go
- itests/markets_v1_deal_test.go
- node/impl/boost.go
- node/impl/boost_legacy.go
Fixes: https://github.com/filecoin-project/boost/issues/301
> Implement MarketImportDealData for backwards compatibility with Bidbot

- gql/resolver_legacy.go
- gql/schema.graphql
- react/src/LegacyDealDetail.js
- react/src/gql.js
- react/src/util.js
- Transferred bytes
- CAR file path
- Piece path
- Available for retrieval
- Funds Reserved
> Show more fields on legacy deal page

- api/api.go
- api/proxy_gen.go
- node/builder.go
- node/config/doc_gen.go
- node/impl/boost_legacy.go
Fixes: https://github.com/filecoin-project/boost/issues/315
> CIDgravity backward compatibility for Boost

- cmd/boost/init.go
- gql/resolver.go
- gql/resolver_legacy_storage.go
- gql/schema.graphql
- node/modules/storageminer.go
- react/src/StorageSpace.css
- react/src/StorageSpace.js
- react/src/gql.js
- storagemanager/storagemanager.go
- util/file.go
> Show storage space used by legacy deals

- cmd/boost/main.go
- cmd/boost/run.go
Fixes: https://github.com/filecoin-project/boost/issues/233
> add pprof to boost

- cmd/boostd/init.go
During `boostd migrate` copy the storage.json file from the existing markets repo, if the file exists. Otherwise create an empty storage.json
> Migrate storage.json

- README.md
Updating the README of Boost with: https://github.com/filecoin-project/boost/blob/nonsense/fix-readme/README.md
> update readme for 3 binaries

- gql/resolver.go
- gql/schema.graphql
- react/src/DealDetail.js
- react/src/gql.js
- react/src/util.js
- Is Verified
- Chain Deal ID
- Transferred
- Client Collateral
- Storage Price Per Epoch
- Storage Fee
- Duration
- Transfer Mode (online / offline)
- Inbound File Path
> Add more fields to deal detail page

- gql/resolver.go
- react/src/DealDetail.css
- react/src/DealDetail.js
> Add tooltip explaining the possible deal states

- cmd/boostx/utils_cmd.go
Fixes: https://github.com/filecoin-project/boost/issues/359
> add car file size

- itests/dummydeal_test.go
- itests/test_framework.go
- node/modules/storageminer.go
- storagemarket/deal_acceptance.go
- storagemarket/provider.go
- storagemarket/provider_test.go
Closes #397 .
We should fetch the ask from the legacy provider.
> Fix ask validation

- react/src/Settings.css
- react/src/Settings.js
- react/src/util.js
https://user-images.githubusercontent.com/169124/162411777-f560b14e-b262-470c-b887-32f78fb242c7.mov
> Show all FIL amounts on settings page as attoFIL

- .circleci/config.yml
- Makefile
- cli/cmd.go
- cli/ctxutil/util.go
- cli/util/api.go
- cmd/boost/provider_cmd.go
- cmd/boostci/main.go
- cmd/boostci/utils_cmd.go
- cmd/boostd/init.go
- cmd/boostx/main.go
- cmd/boostx/utils_cmd.go
This change reduces CI time by about 45 seconds:
Before:
After:
Before:
After:
> Add boostci command with tools to help with CI

- go.mod
- go.sum
Fixes https://github.com/filecoin-project/boost/issues/459
> update libp2p to v0.18.1

- db/db.go
Fixes https://github.com/filecoin-project/boost/issues/456
> Embed imported sql files into binary

- Makefile
- gql/server.go
- react/build/README.md
- react/public/README.md
- react/react.go
Fixes https://github.com/filecoin-project/boost/issues/457
> Serve files over http from embedded fs

- db/deals.go
- db/migrate.go
- db/migrations/20220420124936_setcheckpointattounix0.go
- gql/resolver.go
- gql/schema.graphql
- react/src/DealDetail.js
- react/src/gql.js
- storagemarket/deal_execution.go
- storagemarket/provider_loop.go
- storagemarket/types/deal_state.go
Fixes: https://github.com/filecoin-project/boost/issues/413
> add CheckpointAt field; rename Stage to Checkpoint

- storagemarket/dealfilter/cli.go
Example of the JSON passed to deal filter:
```
{
"DealUUID": "835fbdeb-5649-406a-a2cd-6d9c9f1e6096",
"IsOffline": false,
"ClientDealProposal": {
"Proposal": {
"PieceCID": {
"/": "baga6ea4seaqhiabj4lnvg5nfgoe6xufk3qwdl54wq7qsu7fqrk3vu6axxukccmq"
},
"PieceSize": 2048,
"VerifiedDeal": false,
"Client": "f3qrpvxbzngedntaxibs5th3v42w6ddlk3hupmr5nvl6xbqtvgieax6aikpvawepfuwoiufbzznvkfgt6vseda",
"Provider": "f01000",
"Label": "bafk2bzacearocrcaflv5hesscsbiv64x4om5m64nsh347wedig3nn5l3anypi",
"StartEpoch": 6611,
"EndEpoch": 525011,
"StoragePricePerEpoch": "1",
"ProviderCollateral": "0",
"ClientCollateral": "0"
},
"ClientSignature": {
"Type": 2,
"Data": "i3rKJfAItqmWxiSwPT6VbMUoD8IjOcYkmAJlRAwwr0YjQMdWOByJaUQmRqUGQTdlAeRk/SBdmk+x2sDWXahLWO+XShOiabM2JnT1EmiY0eFVBcMvja6Gm+RZqab6HOtE"
}
}, …
```
> Add version to deal filter json

- cmd/boostd/dummydeal.go
Fixes https://github.com/filecoin-project/boost/issues/470
> hide dummydeal command

- go.mod
- go.sum
Includes https://github.com/filecoin-project/index-provider/commit/563785de47bf47c8ae5ffc407d6fd7294e219a03
> fixes index provider crash

- cmd/boost/deal_cmd.go
Fixes https://github.com/filecoin-project/boost/issues/481
> add 20% to min collateral, when not specified

- cmd/boost/provider_cmd.go
Fixes: https://github.com/filecoin-project/boost/issues/449
TODO:
> provider cmds: storage-ask and retrieval-ask

- cmd/boostd/init.go
- node/builder.go
Fixes https://github.com/filecoin-project/boost/issues/496
> RootDir when migrating Dagstore

- cmd/boost/deal_cmd.go
Fixes: https://github.com/filecoin-project/boost/issues/386
> rename storage-price-per-epoch to storage-price and mul by GiB

- db/deals.go
- db/deals_test.go
- db/fielddef.go
- db/fixtures.go
- db/migrations/20220518162704_deals_addr_binary_to_string.go
- db/migrations/20220520121441_deals_peerid_binary_to_string.go
- db/migrations/migrations.go
- gql/resolver.go
- gql/schema.graphql
- react/package-lock.json
- react/package.json
- react/src/Deals.css
- react/src/Deals.js
- react/src/gql.js
https://user-images.githubusercontent.com/169124/169527929-1b2a5bdc-6629-4df4-8674-4afc4aff645f.mov
> Deal search

- cmd/boost/deal_cmd.go
- cmd/boost/deal_status_cmd.go
```
boost --json deal --provider=t01000 --commp=baga6ea4seaqgbkvk6apsnfbtvnbjabpu4tsv6ns45c36452fdhkqxznt3vlnedq --piece-size=2048 --car-size=1101 --payload-cid=bafk2bzacedsnewk7clxwab2wgwyoi7u5tzdhldx7fkxpqdq7unrxz2zoy4d2g --verified=false --http-url=http://localhost:5000/1k-file.car
{
"clientWallet": "t3r3hr3xl27unpefvipve2f4hlfvdnq3forgr253z6dqahufvanatdandxm74zikheccvx74ys7by5vzafq2va",
"commp": "baga6ea4seaqgbkvk6apsnfbtvnbjabpu4tsv6ns45c36452fdhkqxznt3vlnedq",
"dealUuid": "dac2d8be-e389-4c0f-a8a5-e949e16f38b8",
"endEpoch": "524476",
"payloadCid": "bafk2bzacedsnewk7clxwab2wgwyoi7u5tzdhldx7fkxpqdq7unrxz2zoy4d2g",
"provider": "t01000",
"providerCollateral": "0",
"startEpoch": "6076",
"url": "http://localhost:5000/1k-file.car"
}
boost --json deal-status …
```
> implement --json flag for boost deal and deal-status

- documentation/devnet.md
I have experienced compilation error without this env. variables
> Nessesery environment variables

- cmd/boostd/main.go
- db/migrations/20220531094921_proposal_logs.sql
- db/proposallog.go
- db/proposallog_test.go
- gql/resolver.go
- gql/resolver_proplog.go
- gql/schema.graphql
- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/proplogcleaner.go
- node/modules/storageminer.go
- react/src/App.js
- react/src/DealDetail.js
- react/src/Deals.js
- react/src/Menu.css
- react/src/Menu.js
- react/src/Pagination.css
- react/src/ProposalLogs.css
- react/src/ProposalLogs.js
- react/src/gql.js
- react/src/util-ui.js
- storagemarket/lp2pimpl/net.go
Fixes https://github.com/filecoin-project/boost/issues/548
> UI - proposal logs page

- react/src/Funds.js
- react/src/Info.css
> More explanation on funds page

- README.md
- cmd/boostd/init.go
- documentation/devnet.md
- fundmanager/fundmanager.go
- gql/resolver_funds.go
- gql/schema.graphql
- node/builder.go
- node/config/doc_gen.go
- node/config/types.go
Part of https://github.com/filecoin-project/boost/issues/557
Rename the config value `PledgeCollateral` to `DealCollateral`
When this PR is merged we should update the documentation to change
```
boost init --wallet-pledge-collateral=...
```
to
```
boost init --wallet-deal-collateral=...
```
> Rename PledgeCollateral to DealCollateral

- cli/util/api.go
When running CLI commands, there are a lot of possible ways that the API endpoint can be set: environment variables, flags, etc.
This change will make it easier to track down the root cause of issues like https://github.com/filecoin-project/boost/issues/566
```
$ BOOST_API_INFO=/ip4/127.0.0.1/tcp/1288/http boostd -vv data-transfers list
extracted API endpoint /ip4/127.0.0.1/tcp/1288/http from primary environment variable BOOST_API_INFO
using raw API v0 endpoint: ws://127.0.0.1:1288/rpc/v0
using Boost API endpoint: ws://127.0.0.1:1288/rpc/v0
Error: missing permission to invoke 'MarketListDataTransfers' (need 'write')
```
> Add very verbose logging to CLI API endpoint parsing

- documentation/devnet.md
> docs: improve devnet documentation

- Makefile
Add calibnet flag to the Makefile
> add calibnet flag

- cmd/cmd.go
> Add BOOST_REPO env var

- cmd/boostx/stats_cmd.go
this will allow listing of which storage provider are and are not exporting the standard indexer
> Include indicator of indexer in stats

- react/src/Mpool.js
Fixes https://github.com/filecoin-project/boost/issues/677
> remove fil from gas limit

- react/src/Settings.js
Fixes https://github.com/filecoin-project/boost/issues/631
> fix settings page file size preview

- react/src/Funds.js
Fixes https://github.com/filecoin-project/boost/issues/623
> publish message menu bar-chart

- cmd/boostd/init.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/migrate.go
- node/config/types.go
- node/config/v2_to_v3.go
1. Remove redundant config from boost deal making
2. Update config version to 3
3. Add "HTTPRetrievalMultiaddr" to the file by default
> Update config version to 3

- gql/resolver.go
- gql/resolver_transfers.go
- gql/schema.graphql
- react/src/DealTransfers.css
- react/src/DealTransfers.js
- react/src/Deals.css
- react/src/Deals.js
- react/src/gql.js
- storagemarket/provider.go
- storagemarket/transfer_limiter.go
- storagemarket/transfers.go
Fixes https://github.com/filecoin-project/boost/issues/676
https://user-images.githubusercontent.com/169124/187676717-17aab0c2-8244-4a7c-a35b-a0f2d4bcb64e.mov
> Transfer limiter web UI updates

- docker/devnet/.env
- docker/devnet/boost-gui/Dockerfile.source
- docker/devnet/boost-gui/Makefile
`docker/devnet/boost-gui/Dockerfile.source` had wrong paths. Also changed `version` to be the same as for the boost image
> FIx dockerfile for building react

- storagemarket/deal_execution.go
- storagemarket/provider_test.go
This should fix the problem described at https://github.com/filecoin-project/boost/issues/737#issuecomment-1240300160
> Fail the deal if the transfer fails

- README.md
Fixes https://github.com/filecoin-project/boost/issues/788
> README: fix port for gui

- cmd/booster-bitswap/remoteblockstore/remoteblockstore.go
- cmd/booster-bitswap/run.go
- docker/devnet/.env
- docker/devnet/booster-bitswap/Dockerfile.source
- docker/devnet/booster-bitswap/Makefile
- docker/devnet/booster-bitswap/entrypoint.sh
- docker/devnet/docker-compose.yaml
Initial tracing setup for `booster-bitswap`.
> booster-bitswap devnet and tracing

- react/src/Deals.css
- react/src/Deals.js
> Show legacy deals link at top of deals page

- react/src/Pagination.css
- react/src/Pagination.js
Fixes https://github.com/filecoin-project/boost/issues/841
> add go-to link for pagination

- gql/resolver_legacy.go
- gql/schema.graphql
- react/src/Deals.js
- react/src/LegacyDeals.js
- react/src/gql.js
https://user-images.githubusercontent.com/169124/193296569-1a4e266f-056d-4c4e-964e-0bb3e6f52611.mov
> Search legacy deals by proposal cid

- storagemarket/provider_test.go
Fixes https://github.com/filecoin-project/boost/issues/584
> fix flaky TestMultipleDealsConcurrent

- extern/boostd-data/client/client.go
- extern/boostd-data/go.mod
- extern/boostd-data/go.sum
- extern/boostd-data/ldb/service.go
- extern/boostd-data/svc/couchbase_test.go
- extern/boostd-data/svc/svc.go
- extern/boostd-data/svc/svc_test.go
- go.mod
- go.sum
- node/modules/piecemeta.go
Fixes https://github.com/filecoin-project/boost/issues/896
> use filecoin-project/go-jsonrpc

- extern/boostd-data/couchbase/db.go
- extern/boostd-data/couchbase/service.go
- extern/boostd-data/ldb/db.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/svc/couchbase_test.go
- extern/boostd-data/svc/svc.go
- extern/boostd-data/svc/svc_test.go
- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/piecemeta.go
Fixes https://github.com/filecoin-project/boost/issues/910
> piece directory config

- cmd/migrate-piecedir/main.go
- cmd/migrate-piecedir/migrate_piece_directory.go
Fixes https://github.com/filecoin-project/boost/issues/890
> Piece dir/migrate couch

- cmd/boost/wallet_cmd.go
A small thing that I think could be useful. I've adapted it from lotus.
> Add wallet sign to boost cli

- cmd/boost/wallet_cmd.go
- db/logs.go
- db/logs_test.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/storageminer.go
- storagemarket/logs/log.go
- storagemarket/provider.go
Fixes https://github.com/filecoin-project/boost/issues/924
> Periodic logsDB cleanup based on configured duration

- extern/boostd-data/couchbase/db.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/svc/svc_test.go
- piecemeta/piecemeta.go
- piecemeta/piecemeta_test.go
Make sure that when deals are added to the piece metadata, the list of deals is unique
> add deals to piece metadata uniquely

- extern/boostd-data/ldb/db.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/model/model.go
Remove unused Cursor field from couchbase metadata
> Simplify metadata model

- cmd/boost/wallet_cmd.go
Current output
```
$ boost wallet list
Address                                                                                 Balance  Market(Avail)  Market(Locked)  Nonce  Default  
t1lwygw2bqlir5anhhyhbz2vilazkgpkkedir375i                                                                                                       
0 FIL                                                   
0               
t3rwn4pj4fgncn5nfgxcffitzsjdjgymtfanvnrfom3k32xnag4n5lnzsjwxxfcwjevjur3jhrxqnkkfklj62a                                                          
100 FIL                                                 
0               
X        
0 FIL                                          
0 FIL                           
t3xfilmjuidocvy3247unxdqq42mlr5cmnp6dzsrrkoceygryrycfersndhkkbuastji37q44bk5aogirynauq …
```
> fix: wallet list output

- cmd/booster-http/http_test.go
- cmd/booster-http/mocks/mock_booster_http.go
- cmd/booster-http/run.go
- cmd/booster-http/server.go
- extern/boostd-data/client/client.go
- extern/boostd-data/couchbase/db.go
- extern/boostd-data/couchbase/service.go
- extern/boostd-data/ldb/db.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/svc/types/types.go
- go.mod
- piecemeta/mocks/piecemeta.go
- piecemeta/piecemeta.go
- piecemeta/piecemeta_test.go
Call piece directory service from booster-http (instead of calling boost API methods)
> Integrate piece directory into booster-http

- cmd/boost/wallet_cmd.go
Fixes https://github.com/filecoin-project/boost/issues/950
> feat: show datacap in `boost wallet list`

- go.mod
- go.sum
Until we get resolution on: https://github.com/filecoin-project/go-jsonrpc/pull/84
> use forked go-jsonrpc

- node/config/doc_gen.go
- node/config/types.go
> fix: deal filter description

- go.mod
- go.sum
- gql/resolver.go
- gql/resolver_rtvllog.go
- gql/schema.graphql
- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/retrieval.go
- node/modules/storageminer.go
- react/src/App.js
- react/src/Components.js
- react/src/DealDetail.css
- react/src/Menu.js
- react/src/RetrievalLogDetail.css
- react/src/RetrievalLogDetail.js
- react/src/RetrievalLogs.css
- react/src/RetrievalLogs.js
- react/src/gql.js
- react/src/util-date.js
- retrievalmarket/mock/retrievalmarket.go
- retrievalmarket/rtvllog/create_retrieval_db.sql
- retrievalmarket/rtvllog/db.go
- retrievalmarket/rtvllog/retrieval_log.go
> Retrieval Log page

- node/config/migrate.go
- node/config/v3_to_v4.go
> feat: migrate config to v4

- gql/resolver_piece.go
- gql/schema.graphql
- react/src/Inspect.css
- react/src/Inspect.js
- react/src/gql.js
Mirrors https://github.com/filecoin-project/boost/pull/999 but against the piece directory (instead of dagstore)
> Inspect by non-root cid (piece directory)

- go.mod
- go.sum
- transport/httptransport/libp2p_server.go
Closes: https://github.com/filecoin-project/boost/pull/686
> fix: update to go-libp2p-gostream@v0.5.0

- cmd/booster-http/run.go
Fixes: https://github.com/filecoin-project/lotus/issues/9733
> need empty `StoragePaths`

- cmd/booster-bitswap/filters/blockfilter.go
- cmd/booster-bitswap/filters/filters.go
- cmd/booster-bitswap/run.go
- cmd/booster-bitswap/server.go
fixes https://github.com/filecoin-project/boost/issues/1041
> custom badbits filter

- extern/boostd-data/couchbase/db.go
- extern/boostd-data/couchbase/db_test.go
- extern/boostd-data/couchbase/service.go
- piecedirectory/doctor.go
- piecedirectory/doctor_test.go
- piecedirectory/test_util.go
Based on the number of pieces. eg for 1k pieces check every 10 seconds, for 1m pieces check every hour.
> boost doctor: calculate how often to check each piece dynamically

- react/src/SealingPipeline.js
This prevents the list from constantly changing order
> Sort sealing worker list by date

- build/params.go
- build/params_debug.go
This should make confirmation wait faster in the devnet (eg waiting for deal publish)
> add debug build params

- .circleci/config.yml
- cmd/boostd/piecedir.go
- cmd/booster-bitswap/run.go
- cmd/booster-http/run.go
- cmd/migrate-lid/Makefile
- cmd/migrate-lid/main.go
- cmd/migrate-lid/migrate_lid.go
- extern/boostd-data/client/client.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/svc/svc.go
- gql/resolver_piece.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/piecedirectory.go
- piecedirectory/doctor.go
- piecedirectory/piecedirectory.go
- piecedirectory/piecedirectory_test.go
- react/src/Inspect.js
For now I focused on the externally-facing information, like error messages, and command and parameter names.
Changing all the internal naming would be a lot more work and I'm not sure if it's worth it.
> refactor piece directory -> local index directory

- go.mod
- go.sum
Fixes https://github.com/filecoin-project/boost/issues/1134
> update dagstore to v0.5.7

- cmd/booster-bitswap/filters/filters.go
- cmd/booster-bitswap/filters/filters_test.go
On startup immediately refresh local caches from remote if they are invalid. That might happen due to a previously broken connection that has prevented the process from starting up.
Fixes https://github.com/filecoin-project/boost/issues/1142
> Fetch filters from remote if local cache is invalid

- cmd/booster-http/run.go
- cmd/boostx/main.go
- cmd/boostx/sector.go
- cmd/lib/api.go
Ported from https://github.com/filecoin-project/boost/pull/1069
TODO:
> Port unseal command to main

- go.mod
- go.sum
> update jsonrpc to v0.2.0

- react/src/DealDetail.css
- react/src/DealDetail.js
- react/src/Deals.css
- react/src/Deals.js
- react/src/util.js
> highlight f4 addresses in UI

- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/dealfilter.go
- node/modules/storageminer.go
- storagemarket/provider.go
- storagemarket/provider_dealfilter.go
- storagemarket/provider_loop.go
- storagemarket/provider_test.go
Back ports https://github.com/filecoin-project/boost/pull/1209 and https://github.com/filecoin-project/boost/pull/1210
> hotfix: offline deal slow acceptance and ConsiderOnlineStorageDeals rejection

- storagemarket/dealfilter/cli.go
- storagemarket/provider_dealfilter.go
IsOffline
SkipIPNIAnnounce
RemoveUnsealedCopy
> fix: send more deal params to deal filters

- storagemarket/dealfilter/cli.go
- storagemarket/provider_dealfilter.go
* deal params to filter
* bump agent version json
> port #1213 to main

- storagemarket/contract_deal_monitor.go
- storagemarket/types/contract_deal_proposal_types.go
- storagemarket/types/contract_deal_proposal_types_cbor_gen.go
Integrating with contract at: https://github.com/filecoin-project/fevm-hardhat-kit/pull/90
> FRC DealProposal integration for hyperspace - custom solidity struct

- cmd/lib/api.go
- go.mod
- markets/sectoraccessor/cachingsa.go
- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/storageminer.go
Add a cache that records calls to check if a sector is unsealed
> boost retrieval is unsealed cache

- docker/monitoring/grafana/dashboards/provider-retrievals.json
- metrics/metrics.go
- retrievalmarket/server/gsunpaidretrieval.go
> Add monitoring for graphsync retrievals

- retrievalmarket/rtvllog/retrieval_log.go
> fix: set cancel log to debug level

- retrievalmarket/server/gsunpaidretrieval_test.go
- retrievalmarket/server/validation.go
Fixes https://github.com/filecoin-project/boost/issues/1287
> Disregard unseal price for unpaid retrieval

- storagemanager/storagemanager.go
Fixes https://github.com/filecoin-project/boost/issues/1297
Before:
After:
After storage space is lower than config:
> fix: add free check

- extern/boostd-data/bench/cassandra.go
* Add a connect-string to the cassandra bench command
* Make Cassandra AddIndexRecords retry really hard
> lid bench: Make cassandra put much more robust

- gql/resolver_legacy.go
- gql/schema.graphql
fixes https://github.com/filecoin-project/boost/issues/820
> fix: legacy deal verified status

- cmd/boostd/import_data.go
Fixes https://github.com/filecoin-project/boost/issues/1329
> fix: expand file path

- cmd/boostd/import_data.go
```
boostd import-data 5680556f-9a8e-4b06-997b-15408bc0253b public/sample.car 
Offline deal import for v1.2.0 deal 5680556f-9a8e-4b06-997b-15408bc0253b scheduled for execution
```
> fix: file path bug

- transport/httptransport/libp2p_server_test.go
Fixes https://github.com/filecoin-project/boost/issues/1306
> fix flaky TestLibp2pCarServerNewTransferCancelsPreviousTransfer

- node/modules/graphsync.go
eg https://app.circleci.com/pipelines/github/filecoin-project/boost/3874/workflows/58a2806b-42c9-4793-a868-2311086f43d8/jobs/38671
> fix an occasional panic on shutdown

- gql/serve_download.go
- gql/server.go
- node/builder.go
- node/modules/storageminer.go
- react/src/Inspect.css
- react/src/Inspect.js
Fixes https://github.com/filecoin-project/boost/issues/1309
> Add download block link to inspect page

- Makefile
We've supported building react with Node.js 18 for some time but the Makefile never got fixed. Rather than just bumping the major version to 18 and breaking the build for users still on Node 16, this allows us to specify multiple known good versions. Later we can phase 16 out and 20 in when node 16 hits end of life this year.
A supported node version will show:
```
$ make react
Node.js version v18.12.1 is supported.
npm_config_legacy_peer_deps=yes npm ci --no-audit --prefix react
...
```
and unsupported:
```
$ make react
Unsupported Node.js version. Please install one of the following versions: 16 18
exit 1
make: *** [validate-node-version] Error 1
```
> chore: add support for multiple node.js versions in makefile

- gql/resolver.go
Fixes https://github.com/filecoin-project/boost/issues/1359
TODO:
> Show "verifying commp" message for offline deals

- node/modules/legacy_markets.go
Fixes https://github.com/filecoin-project/boost/issues/1366
TODO:
> fix boost run missing staging-area dir

- db/db.go
- db/deals_test.go
- node/impl/backupmgr/backup.go
Fixes https://github.com/filecoin-project/boost/issues/1362
> fix: backup - db conn hang

- docker/Dockerfile.yugabyte
Login (assuming you have access and permissions to AWS ECR):
```
aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n6b0k8i7
```
Build:
```
docker build -t yugabyte-test -f Dockerfile.yugabyte .
```
Tag with `version` and `arch`, for example:
```
docker tag yugabyte-test:latest public.ecr.aws/n6b0k8i7/yugabyte-test:aarch64-2.13.0.0
```
Push:
```
docker push public.ecr.aws/n6b0k8i7/yugabyte-test:aarch64-2.13.0.0
```
> initial yugabyte dockerfile

- fundmanager/fundmanager.go
- fundmanager/fundmanager_test.go
- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- storagemarket/provider_test.go
> Add a config flag to disable funds tagging

- retrievalmarket/server/gsunpaidretrieval.go
We had reports of panics of `fatal error: concurrent map iteration and map write` at `retrievalmarket/server/gsunpaidretrieval.go:142`
> put g.activeRetrievals behind a lock everywhere

- gql/resolver.go
- storagemarket/deal_execution.go
- storagemarket/lp2pimpl/net.go
- storagemarket/provider.go
- storagemarket/provider_test.go
- storagemarket/smtestutil/mocks.go
Fixes https://github.com/filecoin-project/boost/issues/1398
> fix: fail deal if snap-deal sectors fails sealing

- gql/resolver_mpool.go
> fix: nil pointer error for all messages in UI

- cmd/boostd/import_data.go
Fixes https://github.com/filecoin-project/boost/issues/1472
> fix: incorrect check when import offline deal data using proposal CID

- go.mod
- go.sum
> Update boost-gfm to 1.26.7

- gql/resolver_piece.go
- gql/schema.graphql
- react/src/Info.css
- react/src/Info.js
- react/src/LID.js
- react/src/gql.js
Fixes https://github.com/filecoin-project/boost/issues/1529
Check the unsealed status through both StorageList and SectorsStatus APIs.
If they disagree, it likely means the piece is corrupted.
> Check unseal status of piece through both apis

- docker/monitoring/grafana/dashboards/overview.json
- docker/monitoring/grafana/dashboards/provider-retrievals.json
- docker/monitoring/prometheus-remote-write.yaml
- docker/monitoring/prometheus.yaml
- metrics/metrics.go
1. Updated dashboards
2. Dropped unpopulated dashboards around blockHas requests
3. Removed lotus metrics
> fix: metrics and Grafana

- react/src/Ipni.js
As per suggestion from @gammazero
> web UI: rename indexer config to index provider config

- cmd/boost/retrieve_cmd.go
fixes #1570 
Tested on devnet
```
RETRIEVAL STATS (FIL)                                                                                                                 
-----
Size:          1074 (1.0 KiB)
Duration:      22.354417ms
Average Speed: 48044 (47 KiB/s)
Ask Price:     0 (0 FIL)
Total Payment: 0 (0 FIL)
Num Payments:  0
Peer:          12D3KooWHf7P2ykD9pUNZiWqx5mNZvpKjpFLk9hPbitvfo85qhCi
Saved .car output to /var/lib/boost/output.car
```
> fix: expand retrieve output path

- node/config/doc_gen.go
- node/config/types.go
fixes https://github.com/filecoin-project/boost/issues/1575
> fix: config wallet.miner description

- gql/resolver_maddr.go
- gql/schema.graphql
- react/package-lock.json
- react/package.json
- react/src/App.js
- react/src/MinerAddress.css
- react/src/MinerAddress.js
- react/src/gql.js
Fixes first part of https://github.com/filecoin-project/boost/issues/1621
> Add miner address to top of page in boost UI

- itests/shared/multiminer.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/piecedirectory.go
Fixes https://github.com/filecoin-project/boost/issues/1624
> Move StorageAccessApiInfo config into DealMaking

- extern/boostd-data/client/client.go
- extern/boostd-data/ldb/db.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/yugabyte/piecedoctor.go
- extern/boostd-data/yugabyte/service.go
- gql/resolver_lid.go
- gql/schema.graphql
- piecedirectory/doctor_test.go
- piecedirectory/piecedirectory.go
- react/src/LID.js
- react/src/gql.js
Fixes https://github.com/filecoin-project/boost/issues/1620
> mmlid fixes for LID UI

- extern/boostd-data/yugabyte/migrations/20230824125931_use_timestamptz.sql
- extern/boostd-data/yugabyte/migrations/migrations.go
Fixes https://github.com/filecoin-project/boost/issues/1644
TODO:
> change postgres timezone type to include timezone

- gql/resolver_directdeals.go
- gql/schema.graphql
- react/src/App.js
- react/src/DealDetail.js
- react/src/DirectDealDetail.js
- react/src/gql.js
> feat: direct deals ui - direct deal detail page

- gql/resolver.go
- node/modules/storageminer.go
- react/src/DirectDealDetail.js
- storagemarket/direct_deals_provider.go
- storagemarket/provider_loop.go
> Make retry / fail resolvers work with direct deals

- .circleci/config.yml
https://discuss.circleci.com/t/macos-resource-deprecation-update/46891
> ci: explicitly switch macos build to silicon and upgrade xcode

- transport/httptransport/http_transport_perf_test.go
Add multi stream vs single stream http transfer performance test
> add multistream performance test

- Makefile
- gql/resolver.go
- lib/mpoolmonitor/mpoolmonitor.go
Fixes https://github.com/filecoin-project/boost/issues/1536
> fix: awaiting publish confirmation count

- cmd/boost/wallet_cmd.go
https://github.com/filecoin-project/lotus/pull/11006
> chore: not display privatekey

- lib/mpoolmonitor/mpoolmonitor.go
Fixes: https://github.com/filecoin-project/boost/issues/1798
> fix: fix nil pointer panics in mpoolmonitor

- db/deals.go
Fixes: https://github.com/filecoin-project/boost/issues/1812
> deals: add search by ChainDealID

- cmd/booster-http/run.go
Fixes: https://github.com/filecoin-project/boost/issues/1753
> booster-http: add pprof-port flag

- db/funds.go
- fundmanager/fundmanager.go
- storagemarket/provider.go
Fixes https://github.com/filecoin-project/boost/issues/1851
> feat: cleanup older fund manager logs

- cmd/lib/api.go
Tested with original reported. This is working now.
> fix: sector accessor auth URL handling for ipv6
