filecoin-project/boost

- .gitignore
- cmd/devnet/main.go
- devnet/README.md
- devnet/devnet.go
This PR is adding a devnet command, so that we can easily start a fullnode and a miner, and get `boost` to connect to the miner in order to run end-to-end itests.
> adding fullnode and miner devnet to support boost itests and development

- node/impl/boost.go
Resolves the following error on startup:
```
2021-11-15T16:43:22.250+0100    FATAL   boost   boost/main.go:47        creating node: starting node: could not build arguments for function "reflect".makeFuncStub (/Users/dirk/go/go1.16.9/src/reflect/asm_amd64.s:14): failed to build *sectorblocks.SectorBlocks: missing dependencies for function "reflect".makeFuncStub (/Users/dirk/go/go1.16.9/src/reflect/asm_amd64.s:14): missing type: dtypes.MetadataDS (did you mean dtypes.MetadataDS?)
Exiting.
```
> fix SectorBlocks dependency injection issue

- .github/labels.yml
This copies over labels from Lotus to help with organizing a bit better.
I've simplified the area labels and made them contextual to Boost.
I started setting up some MIlestones and wanted to add some additional issues for
tracking based on what we're shooting for in those milestones, so having these would
be nice for helping to organize a bit more.
> chore: port over some labels from Lotus

- .github/labels.yml
We don't need it and the enhancement label, those are redundant. 
Also, I need to trigger a run of the workflow, due to order of operations problems here setting the workflow up.
> chore: remove improvement label

- gql/resolver_dealpublish.go
- gql/schema.graphql
- react/src/DealDetail.js
- react/src/DealPublish.js
- react/src/gql.js
- react/src/index.css
Add a "Publish Now" button to the batch publish deals page.
When the button is clicked calls a graphql mutation that tells the batch deal publisher to publish all pending deals.
This is equivalent to `lotus-miner storage-deals pending-publish --publish-now`
> ux - publish now

- .circleci/config.yml
- cmd/boost/run.go
- cmd/devnet/main.go
- go.mod
- gql/server.go
- itests/dummydeal_test.go
- pkg/devnet/devnet.go
> initial dummydeal itest for boost with a devnet

- README.md
- cmd/boost/init.go
- cmd/devnet/main.go
- node/builder.go
- node/config/types.go
Fixes: https://github.com/filecoin-project/boost/issues/33
TODO:
> add two wallets as required when initialising boost

- .circleci/config.yml
- cmd/devnet/main.go
- itests/dummydeal_test.go
- pkg/devnet/devnet.go
This should make our integration tests a bit more robust - so far we've always had to clean up the default locations for the lotus-miner and lotus fullnode repository directories. With a temp dir, we don't have to do that, and just leave it to the OS to cleanup on reboot.
---
The `devnet` cmd is still using the user's HOME dir.
> use temporary homedir for filecoin devnet

- .circleci/config.yml
- Makefile
- cmd/boost/dummydeal.go
- db/create.sql
- db/fixtures.go
- db/storage.go
- db/storage_test.go
- gql/dummy.go
- gql/resolver.go
- gql/resolver_mpool.go
- gql/schema.graphql
- itests/dummydeal_test.go
- node/builder.go
- node/modules/storageminer.go
- react/package-lock.json
- react/src/Mpool.css
- react/src/Mpool.js
- react/src/gql.js
- storagemanager/storagemanager.go
- storagemarket/deal_execution.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
- storagemarket/types/dealcheckpoints/checkpoints.go
- testutil/car.go
- testutil/slowreader.go
This PR includes:
- initial Storage Manager implementation
- local filter for mpool
- updated Makefile with builds for both production and debug (2KiB/8MiB sectors)
- fixed dummydeal cmdline tool with correct `StartEpoch` and `EndEpoch`
- `maxDealCollateralMultiplier` hardcoded to 2, instead of 0, which is certainly not correct
- renamed `New` state to `Accepted` 
TODO:
> initial storage manager ; local filter for mpool ; various fixes

- pkg/devnet/devnet.go
This was a rather confusing problem. Obviously we were not fetching anything on this step, so the fetching was happening on the next `lotus-miner` cmd.
> correct params value

- storagemarket/deal_execution.go
For a CARv1 file, using the CARv2 reader over it returns an empty header. We shouldn't use this header to determine the payload size of a CARv1 file and should instead check the size of the file.
> Use correct payload size for a CARv1 file

- cmd/boost/init.go
- cmd/boost/main.go
- gql/resolver.go
- gql/resolver_storage.go
- gql/schema.graphql
- itests/dummydeal_test.go
- node/modules/storageminer.go
- react/src/StorageSpace.js
- react/src/gql.js
- storagemanager/storagemanager.go
- storagemarket/deal_execution.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
This PR is adding the `storageMgr` to the `resolver`, i.e. hooking up the Storage Manager to the GraphQL server and to the React UI.
TODO:
> gql: link storageManager with GraphQL server

- db/create.sql
- db/storage.go
- db/storage_test.go
- storagemanager/storagemanager.go
We are transferring and storing transfers, and not pieces on Boost side, so reflecting this in the model as well.
> refactor: rename pieceSize to transferSize

- cmd/boost/main.go
- gql/resolver_storage.go
- storagemanager/storagemanager.go
Fixes: https://github.com/filecoin-project/boost/issues/159
---
---
This PR is fixing the `pending` overflow, and introduces the following semantics in `boost` with respect to deals storage and boost staging area:
1. `Staging` - when a deal data is successfully transferred, but still stored on `boost` side, it is marked as `Staging`.
2. `Transferred` - bytes transferred for deals that are not yet fully transferred from client to boost
3. `Pending` - bytes to be transferred to `boost`.
4. `Sealing` (not visible in UI yet) - deals that are passed from `boost` to a `sealer` node.
We have to decide how/if we want to visualise storage for deals that are already passed to a sealer node for inclusion in sectors - probably yes, but this is certainly not part of the `markets/boost staging area` …
> storage resolver: fix pending underflow

- go.mod
- go.sum
- node/modules/storageminer.go
- storagemarket/provider.go
- transport/httptransport/http_transport.go
- transport/httptransport/http_transport_test.go
Reuses the http transport we have so we get resumption, notifications etc out of the box.
Augments all tests that we already have for the http transport to use the libp2p-http transport as well.
> Integrate libp2p-http in Boost

- storagemarket/provider.go
- storagemarket/provider_test.go
- storagemarket/provider_transfer_test.go
- testutil/httptestfileservers.go
- transport/httptransport/http_transport.go
- transport/httptransport/http_transport_test.go
- Adds support for three types of test http servers:
- Blocking : Blocks serving the file for a given deal until caller calls unblock for the deal.
- Disconnecting: Serves files from a directory for the corresponding deals but disconnects after sending a configured number of bytes starting at the range offset
- Normal: Serves files from a directory for the corresponding deals.
- Introduces a `testdeal` API that makes it easy to spin up a deal with the required miner stub mocks and http servers and avoids the needs to thread state through actions and assertions.
- Tests for single deal and multiple concurrent deals with a http server that keeps disconnecting.
> Harness support for transfers, transfer disconnect tests and tastier API

- car/car_reader_seeker.go
Simplification is based on the following assumptions for our use case of Boost data-transfers 
- `Seek` will be called only once in the beginning of a transfer before any `Read` call and never again after that.
- `Read` will never be called concurrently with another `Read` or `Seek`.
- Once a transfer is cancelled or a `Read` call errors out, the `CarReadSeeker` will not be used again.
- We spin up one `CarReadSeeker` per http request to the server:
> Simplify car read seeker

- storagemarket/provider_test.go
- testutil/httptestfileservers.go
There was a race where even a disconnecting server could lead to a successful transfer.
> Fix flaky TestDealFailuresHandlingNonRecoverableErrors

- db/funds.go
- db/funds_test.go
- fundmanager/fundmanager.go
- fundmanager/fundmanager_test.go
- storagemarket/deal_execution.go
- storagemarket/logs/log.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
- storagemarket/provider_test.go
- transport/httptransport/http_transport_test.go
- Don't log client signature and transfer params other than the URL.
- Use a non-cancellable context for important db updates such as checkpoints and logging.
- Better logging for transfer progress.
- Better logging for funds tagging and untagging.
- Remove unnecessary chatter from deal resumption logs.
> Fixes based on integration testing

- cmd/boost/init.go
I forgot to add this to the main `boost` binary, I only had it in tests.
> add miner addr to datastore

- storagemarket/deal_execution.go
- storagemarket/provider_test.go
For some reason, the Miner API's error isn't unwrapping as a context cancellation so need to do this.
Also fixes the flaky deal funds test by ensuring the deals terminate so db files can be cleanedup.
> Resume publish confirmation

- go.mod
- itests/markets_v1_deal_test.go
This PR is adding retrieval after a MarketsV1 deal is sealed on the devnet, and confirms that retrieval works on Boost with MarketsV1 protocols.
> add retrieval itest after deal is sealed for markets v1

- .circleci/config.yml
- go.mod
- go.sum
- itests/main_test.go
- node/modules/client.go
Technically this is not syncing with `lotus@master`, but rather with https://github.com/filecoin-project/lotus/pull/8086 which is rebase on `lotus@master`.
> upgrade to lotus@master

- cmd/boost/main.go
If we don't over-write the setting it allows us to set the log level via env vars, eg:
```
GOLOG_LOG_LEVEL=info,connmgr=warn,net/identify=warn,dht/RtRefreshManager=warn boost run
```
> Dont over-write log level set by env vars

- api/market.go
- api/proxy_gen.go
- cmd/boost/deals.go
- cmd/boost/main.go
- db/create_main_db.sql
- db/deals.go
- db/deals_test.go
- db/fixtures.go
- itests/dummydeal_test.go
- itests/test_framework.go
- node/impl/boost.go
- storagemarket/deal_execution.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
- storagemarket/provider_offline_test.go
- storagemarket/provider_test.go
- storagemarket/types/deal_state.go
- storagemarket/types/types.go
- storagemarket/types/types_cbor_gen.go
Closes https://github.com/filecoin-project/boost/issues/197
> offline deal support in Boost

- storagemanager/storagemanager.go
- storagemarket/provider.go
I guess `mount point` should be pointing to `incoming` ?
> staging area for boost

- api/market.go
- api/proxy_gen.go
- cmd/boostd/dagstore.go
- cmd/boostd/index.go
- cmd/boostd/main.go
- go.mod
- indexprovider/wrapper.go
- node/builder.go
- node/impl/boost.go
- node/modules/storageminer.go
- storagemarket/provider_loop.go
- storagemarket/provider_test.go
- storagemarket/types/types.go
- Starting legacy markets will take care of marking legacy deals for dagstore migration.
> Dagstore Shard migration for Boost deals

- .circleci/config.yml
- Makefile
This PR adds the following targets to Makefile:
- `make react` - Building all React source
- `make build` - React target is now part of `make build`
> make react

- cmd/boostd/init.go
- cmd/boostd/main.go
Also output a nicer error message if a required environment variable is not set:
```
$ ./boostd -vv init --api-sealer=$MINER_API_INFO --api-sector-index=$MINER_API_INFO --wallet-publish-storage-deals=$PUBMSG_WALLET --wallet-collateral-pledge=$COLLAT_WALLET --max-staging-deals-bytes=2000000000
Initializing boost repo
Trying to connect to full node RPC
Error: could not get API info for StorageMiner: could not determine API endpoint for node type: StorageMiner
Do you need to set the environment variable MINER_API_INFO?
```
> Send output of boostd init and boostd migrate to stdout instead of log file

- node/builder.go
- node/modules/provider_data_transfer.go
Ideally we shouldn't have to do that, and maybe we can achieve the same thing with: https://github.com/uber-go/fx/blob/v1.17.1/app.go#L151
However it'd be nice to know if we mess up a shutdown elsewhere, so I'd rather just isolate the `datatransfer.Manager` for now.
---
```
goroutine 420444 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc019a6c9a0)
/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc019a6c998)
/usr/local/go/src/sync/waitgroup.go:130 +0x65
golang.org/x/sync/errgroup.(*Group).Wait(0xc019a6c990, 0xc01da64e20, 0xc0600ebbd8)
/root/code/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x31
github.com/filecoin-project/go-data-transfer/transport/graphsync.(*Transport).Shutdown(0xc014fc4a00, 0x4b11358, 0xc000058120, 0x0, …
```
> timeout of 5sec. for datatransfer.Manager.Stop()

- storagemarket/deal_execution.go
Upon deal resumption, we should expect the inbound file to exist  only if it hasn't already been handed over to the sealer.
> Fix restart after add piece

- db/deals.go
- db/deals_test.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
There's a edge case where we wont cleanup a deal on resumption if it has already been marked completed even though Boost restarted after the deal was previously marked as completed but not cleaned up.
> Cleanup completed deals on restart

- cmd/boost/deal_status_cmd.go
```
$ ./boost deal-status --provider=t01000 --deal-uuid=1c3fdde2-2d30-4422-bab6-68aef81e118d
got deal status response
deal uuid: 1c3fdde2-2d30-4422-bab6-68aef81e118d
deal status: Error: failed to publish deal: failed to publish deal 1c3fdde2-2d30-4422-bab6-68aef81e118d: publish validation failed: cannot publish deal with piece CID baga6ea4seaqklovg65cl5aw3o7vmynkgenbmiaz422yyp6ooyvrzmzt5etquibq: current epoch 116815 has passed deal proposal start epoch 115792
deal label: bafk2bzacecklzvh7bw7eyk5md34yznkeeaar4l7hauwovs5l7kquwr7i4gwb4
publish cid: bafy2bzaced6covug2oh5cbga2lfdc43e5zpywqhbxmsd36j44t4ymiocebiwk
chain deal id: 48
```
> deal status: show error if deal failed

- .github/workflows/main.yml
This PR adds a new workflow that will assign any added issues to the Boost project - https://github.com/orgs/filecoin-project/projects/29. I will create another PR to do this in the boost-docs repo as well.
I've added a BOOST_BOARD secret to the boost and boost-docs repo with minimal permissions to perform the action of assigning issues to the project via the graphql endpoint. This token is set to a 90 day expiration and will need to be rotated by then.
This replicates the flow at https://github.com/filecoin-project/ref-fvm/pull/357, but does not include an assigned status since we don't use defaults in the boost project.
> chore: add workflow to assign new issues to project board

- cli/node/node.go
- cmd/boost/deal_cmd.go
- cmd/boost/deal_status_cmd.go
- cmd/boost/helper.go
- cmd/boost/main.go
- cmd/boost/wallet_cmd.go
- cmd/boostx/utils_cmd.go
Fixes: https://github.com/filecoin-project/boost/issues/414
> initial wallet support for boost

- fundmanager/fundmanager.go
- itests/dummydeal_test.go
- storagemanager/storagemanager.go
- storagemarket/deal_acceptance.go
- storagemarket/lp2pimpl/net.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
- storagemarket/provider_offline_test.go
- storagemarket/provider_test.go
Instead of just closing the connection:
```
$ ./boost deal \
--provider=t01000 \
--commp=baga6ea4seaqhiabj4lnvg5nfgoe6xufk3qwdl54wq7qsu7fqrk3vu6axxukccmq \
--piece-size=2048 \
--car-size=1101 \
--payload-cid=bafk2bzacearocrcaflv5hesscsbiv64x4om5m64nsh347wedig3nn5l3anypi \
--verified=false \
--http-url=http://localhost:5000/1k-file.car
2022-04-12T11:46:35.278+0200	FATAL	boost	boost/main.go:41
deal proposal rejected: server error: provider has insufficient funds to accept deal
```
Fixes https://github.com/filecoin-project/boost/issues/433
> Send deal rejection reason to client

- go.mod
- go.sum
- gql/resolver.go
- gql/server.go
- react/src/Deals.css
- react/src/Deals.js
- react/src/Info.css
- react/src/Info.js
- react/src/gql.js
> Fix web UI connect errors

- cli/node/node.go
- cmd/boost/deal_cmd.go
- cmd/boost/deal_status_cmd.go
- cmd/boost/init_cmd.go
- cmd/boost/main.go
- cmd/boost/provider_cmd.go
- cmd/boost/wallet_cmd.go
- cmd/boostx/utils_cmd.go
- cmd/cmd.go
- cmd/util.go
Adds a `provider` category with a `libp2p-info` command:
```
$ FULLNODE_API_INFO="https://api.node.glif.io" ./boost provider libp2p-info f0127896
Provider: f0127896
Peer ID: 12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ
Peer Addresses:
/ip4/85.11.148.122/tcp/24001
Protocols:
/fil/datatransfer/1.2.0
/fil/kad/testnetnet/kad/1.0.0
/fil/retrieval/qry/0.0.1
/fil/retrieval/qry/1.0.0
/fil/storage/ask/1.0.1
/fil/storage/ask/1.1.0
/fil/storage/mk/1.0.1
/fil/storage/mk/1.1.0
/fil/storage/mk/1.2.0
/fil/storage/status/1.0.1
/fil/storage/status/1.1.0
/fil/storage/status/1.2.0
/floodsub/1.0.0
/ipfs/graphsync/1.0.0
/ipfs/graphsync/2.0.0
/ipfs/id/1.0.0
/ipfs/id/push/1.0.0
/ipfs/ping/1.0.0
/legs/head//indexer/ingest/mainnet/0.0.1
/libp2p/autonat/1.0.0
/meshsub/1.0.0
/meshsub/1.1.0 …
```
> cli: add boost provider libp2p-info command

- cmd/boost/main.go
- cmd/boost/provider_cmd.go
```
$ FULLNODE_API_INFO="https://api.node.glif.io" ./boost --json provider libp2p-info f01234
{
"agent": "lotus-1.15.2-dev+mainnet",
"id": "12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ",
"multiaddrs": [
"/ip4/85.11.148.122/tcp/24001"
],
"protocols": [
"/fil/datatransfer/1.2.0",
"/fil/kad/testnetnet/kad/1.0.0",
"/fil/retrieval/qry/0.0.1",
"/fil/retrieval/qry/1.0.0",
"/fil/storage/ask/1.0.1",
"/fil/storage/ask/1.1.0",
"/fil/storage/mk/1.0.1",
"/fil/storage/mk/1.1.0",
"/fil/storage/mk/1.2.0",
"/fil/storage/status/1.0.1",
"/fil/storage/status/1.1.0",
"/fil/storage/status/1.2.0",
"/floodsub/1.0.0",
"/ipfs/graphsync/1.0.0",
"/ipfs/graphsync/2.0.0",
"/ipfs/id/1.0.0",
"/ipfs/id/push/1.0.0",
"/ipfs/ping/1.0.0",
"/legs/head//indexer/ingest/mainnet/0.0.1",
"/libp2p/autonat/1.0.0", …
```
> Add agent version to boost provider libp2p-info

- cmd/boostx/confirm.go
- cmd/boostx/main.go
- cmd/boostx/utils_cmd.go
Fixes: https://github.com/filecoin-project/boost/issues/450
---
Also adding a `confirm` interactive screen:
```
➜  boostx market-add --wallet=f1sw5zjcyo4mff5cbvgsgmm7uoko6gcr4tptvtkhy 0.3
2022-04-21T14:16:59.059+0300    INFO    boostx  boostx/utils_cmd.go:82  selected wallet {"wallet": "f1sw5zjcyo4mff5cbvgsgmm7uoko6gcr4tptvtkhy"}
about to send message with the following gas costs
gas fee cap:  0.000000000307874188 FIL
gas limit:    13517058
gas premium:  0.000000000000000073 FIL
basefee:      0.000000000153937094 FIL
Proceed? Yes [y] / No [n]:
```
> add market-withdraw cmd to boostx

- react/src/SealingPipeline.js
"No active workers" is somewhat confusing, as reported by stuberman:
```
I also wonder why on the GUI the ‘sealing pipeline’ shows: Workers No active workers despite having a sealing worker that is standing by for sectors
```
---
So changing to "No active jobs"
> change to "No active jobs"

- go.mod
- go.sum
- itests/dummydeal_test.go
- node/builder.go
- node/modules/storageminer.go
Fixes https://github.com/filecoin-project/boost/issues/492
- The legacy StorageProvider returns from it's Start method before registering the multihash lister for the DAG store
- The boost StorageProvider should overwrite the multihash lister, but sometimes Boost's start method will run before legacy StorageProvider has registered its multihash lister
- The solution is to
- ensure that the legacy SP only fires the `ready` event after the multihash lister has been registered https://github.com/filecoin-project/go-fil-markets/pull/708
- ensure that Boost SP waits to start until the `ready` event has been fired by the legacy SP (this PR)
> fix index provider register multihash lister

- db/fixtures.go
- gql/resolver.go
- gql/schema.graphql
- react/src/DealDetail.css
- react/src/DealDetail.js
- react/src/gql.js
- storagemarket/deal_execution.go
- storagemarket/deal_handler.go
- storagemarket/provider.go
- storagemarket/provider_loop.go
- storagemarket/provider_test.go
Updates the web UI to add buttons to retry and terminate a deal that is in the Paused state.
As part of the PR I needed to
- Add a FailPausedDeal endpoint
- Do some refactoring of the deal handler to enable this new endpoint
> Deal retry web UI

- Makefile
```
$ nvm use v17.0.1
Now using node v17.0.1 (npm v8.1.0)
$ make
Build requires Node v16 (detected Node v17.0.1)
make: *** [check-node-lts] Error 1
$ nvm use v16.12.0
Now using node v16.12.0 (npm v8.1.0)
$ make
Building using Node v16
npm install --prefix react
...
```
> Require specific node version for Make

- Makefile
Fixes https://github.com/filecoin-project/boost/issues/567
Unfortunately it's not really possible to fix this properly, as explained in https://github.com/facebook/create-react-app/issues/11174
Because the web interface is not exposed to the internet anyway we can just suppress the audit warnings.
> fix spurious node warnings

- react/src/DealTransfers.js
Also add a UI cue that the transfer rate in the menu item is averaged over 10s
> When displaying transfers, always fetch from network (no caching)

- Makefile
Since not all of our node dependencies are locked in `package.json`, `npm install` upgrades them whenever possible. (more background at: https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json)
I think it is preferable that we have reproducible builds and build packages as they are defined in `package-lock.json`, so I suggest we change to `npm ci` and occasionally on-demand upgrade our dependencies.
> replace npm install with npm ci

- cmd/boost/wallet_cmd.go
Relates to #469 
List of commands (`boost --json wallet <command>`) to implement json support for:
> feat: support json output in the `boost wallet` command

- go.mod
- go.sum
Upgrade to the offset writer branch rebased on top of fix to minimum
index width released in v2 `2.4.1`.
> Upgrade to latest `go-car` rebase of offset writer

- transport/httptransport/libp2p_server.go
We can just use the libp2p network Stream
> fix: dont use the gostream patch

- cmd/boostx/stats_cmd.go
This PR is also adding stats about Boost providers in terms of quality adjusted power and raw power.
At the end we will have an idea and stats around the power of Boost providers in the network.
> add power to boostx stats

- README.md
> update readme to refer to docs

- car/car_offset_writer.go
- car/car_offset_writer_test.go
Ref: https://github.com/filecoin-project/boost/issues/673#issuecomment-1202312003
Ideally we can remove go-merkledag entirely from here because most (all?) of the deal-making infrastructure uses go-codec-dagpb + go-ipld-prime traversals and post-decode link-reordering is a subtle difference that impacts CAR ordering for non-spec-compliant DAG-PB blocks.
But for now, this is a quick-fix that should preserve the links in the order as they are appear in the block, which is what our other traversals are working with.
> fix: don't allow go-merkledag to reorder loaded links

- .circleci/config.yml
xcode 12.5.0 is no longer supported by circleCI
https://circleci.com/docs/testing-ios
> chore: update xcode version to supported

- db/db.go
- node/modules/storageminer.go
Follow up from https://github.com/filecoin-project/boost/pull/657
> Fix 'database is locked' error

- cmd/boostd/init.go
Fixes https://github.com/filecoin-project/boost/issues/700
Tested on my local devnet:
```
[Dealmaking]
ConsiderOnlineStorageDeals = true
ConsiderOfflineStorageDeals = true
ConsiderOnlineRetrievalDeals = true
ConsiderOfflineRetrievalDeals = true
ConsiderVerifiedStorageDeals = true
ConsiderUnverifiedStorageDeals = true
PieceCidBlocklist = []
ExpectedSealDuration = "24h0m0s"
MaxDealStartDelay = "336h0m0s"
PublishMsgPeriod = "1h0m0s"
PublishMsgMaxDealsPerMsg = 8
PublishMsgMaxFee = "0.05 FIL"
MaxProviderCollateralMultiplier = 2
MaxStagingDealsBytes = 200000
SimultaneousTransfersForStorage = 20
SimultaneousTransfersForRetrieval = 20
StartEpochSealingBuffer = 480
DealProposalLogDuration = "24h0m0s"
Filter = ""
RetrievalFilter = ""
MaxTransferDuration = "24h0m0s"
[Dealmaking.RetrievalPricing] …
```
> When migrating from lotus start from default config

- cmd/boost/deal_status_cmd.go
- node/modules/storageminer.go
- storagemarket/lp2pimpl/net.go
- storagemarket/types/types.go
- storagemarket/types/types_cbor_gen.go
Supersedes https://github.com/filecoin-project/boost/pull/697
Fixes https://github.com/filecoin-project/boost/issues/696
```
$ boost --json deal-status --deal-uuid=f1ffaa64-3249-4173-b008-572b35e1e81e --provider=t01000
{
"chainDealId": 1,
"clientWallet": "t3r3hr3xl27unpefvipve2f4hlfvdnq3forgr253z6dqahufvanatdandxm74zikheccvx74ys7by5vzafq2va",
"dealUuid": "f1ffaa64-3249-4173-b008-572b35e1e81e",
"label": "bafk2bzacedsnewk7clxwab2wgwyoi7u5tzdhldx7fkxpqdq7unrxz2zoy4d2g",
"provider": "t01000",
"publishCid": "bafy2bzacea7cohv4zexvyyv5hwgdauaajcb6w74bn2yxfymy57ywam6xpyneq",
"sealingStatus": "Proving",
"status": "IndexedAndAnnounced",
"statusMessage": "Sealing: Proving"
}
```
> send sealing status in deal status response

- cmd/boost/provider_cmd.go
- cmd/boost/provider_cmd_test.go
- go.mod
- go.sum
- node/builder.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/retrieval.go
- retrievalmarket/lp2pimpl/transports.go
- retrievalmarket/types/transports.go
- retrievalmarket/types/transports.ipldsch
Fixes https://github.com/filecoin-project/boost/issues/717
TODO:
```
$ boost provider retrieval-transports t01000
libp2p
/ip4/192.168.1.11/tcp/50000
/ip4/127.0.0.1/tcp/50000
/ip6/::1/tcp/65450
http
/dns/foo.com/tcp/443/https
https://foo.com:443
$ boost --json provider retrieval-transports t01000
{
"http": [
{
"multiaddr": "/dns/foo.com/tcp/443/https",
"address": "https://foo.com:443"
}
],
"libp2p": [
{
"multiaddr": "/ip4/192.168.1.11/tcp/50000"
},
{
"multiaddr": "/ip4/127.0.0.1/tcp/50000"
},
{
"multiaddr": "/ip6/::1/tcp/65450"
}
]
}
```
> libp2p retrieval transports endpoint

- cmd/booster-http/server.go
```
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 1101
< Content-Type: application/vnd.ipld.car
< Etag: baga6ea4seaqgbkvk6apsnfbtvnbjabpu4tsv6ns45c36452fdhkqxznt3vlnedq.car
< Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT
< Date: Wed, 24 Aug 2022 09:48:06 GMT
```
> set booster-http cache control headers

- cmd/booster-http/server.go
In https://github.com/filecoin-project/boost/pull/718 we disabled extracting the CAR file for HEAD requests. However this results in an incorrect `Content-Length` header, so this PR re-enables extracting the CAR file even for HEAD requests.
> Fix Content-Length header in HEAD request for CAR file

- go.mod
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/storageminer.go
- storagemarket/deal_execution.go
- storagemarket/provider.go
- storagemarket/provider_test.go
- storagemarket/transfer_limiter.go
- storagemarket/transfer_limiter_test.go
- storagemarket/types/types.go
- storagemarket/types/types_test.go
- transport/httptransport/http_transport.go
- transport/httptransport/util/util.go
- transport/httptransport/util/util_test.go
Fixes https://github.com/filecoin-project/boost/issues/705
Currently boost starts a new download for every storage deal that it receives. If a client sends 1000 deals, boost will open 1000 concurrent connections. Because bandwidth is limited, these downloads will proceed very slowly. Meanwhile the sealing pipeline will sit idle until a transfer finishes.
The Storage Provider should be able to adjust a parameter to limit the number of parallel transfers, so that they can keep their sealing pipeline busy.
For simplicity this PR only uses a single config value: an overall "soft" limit on the number of transfers.
See the explanation at https://github.com/filecoin-project/boost/pull/710/files#diff-dafd8b081e95b0e754470a4a23253b2e4a08ba06390015ac77d0e9a59cbe3a5aR30-R54
> Transfer limiter

- node/impl/boost.go
the check keep failing each time for errored out shards. We should directly issue a deleted instead of checking. incorrect CID will be covered by error thrown from destroy call itself.
> fix: dagstore destroy-shard

- docker/devnet/docker-compose.yaml
This PR is changing the default network name of the devnet from `devnet_default` to `devnet`. The idea is that we'll have to connect other containers to it, i.e. `prometheus` and/or `tempo` and maybe others from the `monitoring` stack.
cc @airenas
> change network name for devnet

- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/storageminer.go
- storagemarket/deal_commp.go
- storagemarket/provider.go
- storagemarket/transfer_limiter_test.go
Supersedes https://github.com/filecoin-project/boost/pull/714
Adds a config option to throttle the number of commp threads that can run in parallel in the boost process:
```
[Dealmaking]
MaxConcurrentLocalCommp = 1
```
> Throttle local commp

- cmd/booster-http/run.go
- docker/devnet/booster-http/entrypoint.sh
Adds a `--enable-tracing` flag to booster-http. The flag is false by default, preventing the instantiation and startup of the tracing exporter. The flag is set to true for the devnet docker setup. Part of #774.
> Add --enable-tracing flag to booster-http

- storagemarket/deal_execution.go
Output a log line to the deal log (the log on the deal detail page) each time the sealing state changes
> Output sealing state changes to the deal log

- cmd/boostd/run.go
- cmd/booster-http/run.go
- docker/devnet/booster-http/entrypoint.sh
- docker/devnet/docker-compose.yaml
- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/impl/boost.go
- node/modules/storageminer.go
- tracing/exporter.go
- tracing/tracing.go
This PR is adding the `[Tracing]` configuration section in the Boost node config.toml
It also moves the instantiation of the tracing system within the Boost node dependency injection.
It is also renaming the flag on `booster-http` from `--enable-tracing` to just `--tracing`, and adds `--tracing-endpoint`.
> tracing behind feature-flag for boostd; configuration in config.toml

- .dockerignore
- docker/devnet/Makefile
- docker/devnet/boost/Dockerfile.source
- docker/devnet/boost/Makefile
Resolves #767
This solution adds optimization for building docker image for the boost only, it does not deal with building the lotus.
**Improvements:**
1. caches *filecoin-ffi* build. It was a bit problematic, as a makefile of the *filecoin-ffi* depends on a git. We don't want the cache to be cleared on any git commit... etc. So I made a solution to do `git submodule update` before `docker build` command.  
2. caches go.mod downloads
3. caches `go build` using docker's buildkit feature
My rough estimates of the building time:
```bash
###########################################################
$ time (cd ../../ && make debug)
...
real	0m28.465s
###########################################################
time make build/boost docker_args=--no-cache
...
=> [builder  2/12] RUN apt update && …
```
> Docker boost speedup

- cmd/boostd/init.go
Currently, `init` and `migrate` forces the users to use separate the wallet for collateral and MessagePublish. This PR removes the check to allow use of a single wallet for both.
> Remove single wallet restriction

- cmd/booster-bitswap/remoteblockstore/remoteblockstore.go
- cmd/booster-bitswap/remoteblockstore/remoteblockstore_test.go
Return [ipld ErrNotFound](https://github.com/ipfs/go-ipld-format/blob/master/merkledag.go#L15) from GetSize() if the block is not found, because [Bitswap checks for this error](https://github.com/ipfs/go-bitswap/blob/4e3736a773545bf09d5178a2be24043b76560f87/server/internal/decision/blockstoremanager.go#L97) to decide if a block is present.
Note that the RemoteBlockstore calls across an RPC boundary, so the code needs to do string matching to check if the error message matches the ipld ErrNotFound error.
> return ipld ErrNotFound from remote blockstore interface

- itests/dummydeal_test.go
Part of TestDummydealOnline fails because of a bug in the latest version of lotus, introduced in [feat: message: Add uuid to mpool message sent to chain node from miner](https://github.com/filecoin-project/lotus/pull/9174/files#top)
So disable that part of the test until the bug is fixed.
> Comment out part of TestDummydealOnline

- .dockerignore
- docker/devnet/boost/Dockerfile.source
Additional fix for #788:
- it makes sure a react GUI is packed into a boost container. It was not the case on a clean git repo
- uses a separate node image to build the react app and copies binaries to the boost builder
> Add react GUI to boost docker

- docker/monitoring/grafana/dashboards/exported_dashboard.json
Adds pprof metrics for booster-http to the grafana dashboard in the docker monitoring stack.
Updates #772
> Add booster-http pprof metrics to grafana dashboard

- docker/devnet/docker-compose.yaml
- docker/monitoring/grafana/dashboards/exported_dashboard.json
- docker/monitoring/prometheus.yaml
Adds pprof metrics for boostd to the grafana dashboard in the docker monitoring stack.
- Exposes port `1288`, which the web server with the `/metrics` handler is running on
- Adds a scraping job of the `boost:1288` addresss to the `docker/monitoring/prometheus.yaml` config
- Adds an example stat and the pprof stats to the grafana dashboard
Grafana Dashboard Updates
Fixes #772
> Add boostd pprof metrics to grafana dashboard

- .dockerignore
Fix a problem introduced by: https://github.com/filecoin-project/boost/commit/207b5cc10633acbbb6db78b01bef7116d013f2dc
I wanted to speed up boost container build, but it turned out other containers also depend on `react/build`.
> Fix failing build for booster-http docker

- README.md
Necessary so that Prometheus can scrape targets from the devnet stack.
> update readme for prometheus

- cmd/booster-http/server.go
- docker/monitoring/grafana/dashboards/exported_dashboard.json
- metrics/metrics.go
Adds metrics for booster-http response codes counts for both Payload by Cid and Piece by Cid to the monitoring Grafana dashboard. Adds counts for 200, 400, 404, and 500 status codes over 30 second intervals.
- Payload by CID Status Response Counts
- Piece by CID Status Response Counts
Updates #824
> Add http response code metrics to dashboard

- cmd/booster-bitswap/blockfilter/blockfilter.go
- cmd/booster-bitswap/blockfilter/blockfilter_test.go
- cmd/booster-bitswap/remoteblockstore/remoteblockstore.go
- cmd/booster-bitswap/run.go
- cmd/booster-bitswap/server.go
Provide a mechanism for filtering out illegal CID requests in bitswap.
- This implements a lightweight block filter module that fetches the bad bits list and checks bitswap requests against what is in the list.
- The list downloads and updates every five minutes in the background -- currently, it's only 1meg large
- The in place block check is O(1) against an in memory copy of the list (currently, again, not a serious memory overhead)
- integrates the block filter into the remote blockstore in booster bitswap
- Currently, this lives inside of booster bitswap -- should it instead live inside of boost and possibly the block API calls?
- I didn't put optimization around passing If-Not-Modified as request header and checking for a 304 Not Modified response -- this may be prudent as the list …
> Add block filter via BadBits

- docker/monitoring/grafana/dashboards/exported_dashboard.json
- metrics/metrics.go
Registers the lotus/metrics dagstore metrics to boost's prometheus exporter to display in the monitoring stack Grafana dashboard. All panels are counts over a 30 second interval.
**Note:** I don't have a ton of context into what these values should be during runtime, so if there's any additional context that can provided that may make any of these panels more helpful, let me know. I wasn't sure if the Init Count value changes over time or is actually a constant upon start, for example.
- Registers lotus dagstore metrics with the boost metrics exporter
- Adds the following panels to the dasboard
- Dagstore PieceReader Init Count (Not sure if this value changes over time or is a constant. Made it a timeline just in case.)
- Dagstore PieceReader Requested Bytes
- Dagstore PieceReader Discard …
> Register lotus dagstore metrics with prometheus exporter

- cmd/booster-bitswap/init.go
- node/config/doc_gen.go
- node/config/types.go
Follow on to #786 , per @dirkmc suggestions
> Protocol Proxy cleanup

- docker/devnet/docker-compose.yaml
- docker/monitoring/prometheus.yaml
Adds a prometheus scrape configuration for the lotus-miner devnet container so that we can visualize any lotus-miner metrics in the monitoring Grafana dashboard.
> Add prometheus scrape config for lotus-miner

- docker/monitoring/prometheus.yaml
Unlike `boostd`, and `booster-http`, the metrics path for `lotus-miner` is at `/debug/metrics`:
> add metrics-path

- cmd/booster-bitswap/remoteblockstore/remoteblockstore.go
- cmd/booster-bitswap/remoteblockstore/remoteblockstore_test.go
We are seeing a lot of extraneous "not found" errors in the logs:
```
2022-10-04T16:13:59.899+0300    ERROR   engine  decision/blockstoremanager.go:99        blockstore.GetSize(QmegVFK7NszHq6BG3Lu2kKQ6YkKjyhWwaZ28i2M2mCRPQi) error: block not found
2022-10-04T16:13:59.899+0300    ERROR   engine  decision/blockstoremanager.go:99        blockstore.GetSize(bafkreiccq5bf6vm7pmnvz26hcqmkbtpayg3srhpsenq6dzy2565qjbt6wy) error: block not found
2022-10-04T16:13:59.899+0300    ERROR   engine  decision/blockstoremanager.go:99        blockstore.GetSize(bafybeicoprmqmoztnidjg4u5gqg33cz36heglyoyl6lgeznsvg5z7pdwty) error: block not found
```
This is because
- bitswap expects ipld ErrNotFound if the block is not found
- different parts of the system return different "not found" errors (eg ipld …
> Translate all not found errors to ipld ErrNotFound for bitswap

- cmd/booster-bitswap/init.go
- cmd/booster-bitswap/main.go
- cmd/booster-bitswap/run.go
- cmd/booster-bitswap/server.go
- docker/devnet/.env
- docker/devnet/boost/sample/random.sh
- docker/devnet/booster-bitswap/entrypoint.sh
- docker/devnet/docker-compose.yaml
- protocolproxy/forwardinghost.go
- protocolproxy/forwardinghost_test.go
- protocolproxy/protocolproxy.go
Fixes https://github.com/filecoin-project/boost/issues/865
Sample output:
```
2022-10-04T18:01:43.849+0300    INFO    booster booster-bitswap/run.go:106      Starting booster-bitswap node on port 24006
2022-10-04T18:01:43.849+0300    INFO    booster booster-bitswap/server.go:43    connecting to proxy     {"proxy": "{12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ: [/ip4/85.11.148.122/tcp/24001]}"}
2022-10-04T18:01:43.855+0300    INFO    booster booster-bitswap/server.go:72    bitswap server running  {"multiaddrs": ["/ip4/192.168.0.109/tcp/24006","/ip4/127.0.0.1/tcp/24006","/ip4/192.168.0.109/udp/24006/quic","/ip4/127.0.0.1/udp/24006/quic"], "peerId": "12D3KooWGk5Q7vHfemk5iu8a9e3W6b5xPLVEw85KGMcX2EDhMjo9"}
2022-10-04T18:03:53.858+0300    WARN    booster booster-bitswap/server.go:96 …
```
> keep connection between booster-bitswap and proxy alive

- cmd/booster-bitswap/remoteblockstore/remoteblockstore.go
- cmd/booster-bitswap/run.go
- cmd/booster-bitswap/server.go
- docker/monitoring/prometheus.yaml
- metrics/metrics.go
Setups the metrics infrastructure and adds metrics for booster-bitswap request and response counts for the `RemoteBlockstore` `Get`, `Has`, and `GetSize` functions to the monitoring Grafana dashboard. Adds counts for requests, and both success and fail responses. All counts show results over a 30 second interval.
- Adds metrics webserver on booster-bitswap server `Start` to `0.0.0.0:1234`
- Adds prometheus scrape job to scrape booster-bitswap `/metrics` endpoint
- Records request counts, success, and fail response counts for `RemoteBlockstore` `Get`, `Has`, and `GetSize`
- Adds request counts for `RemoteBlockstore` `Get`, `Has`, and `GetSize`
- Adds response counts for `RemoteBlockstore` `Get`, `Has`, and `GetSize`
- Adds an overall Bitswap Success / Failure rate that encompasses all …
> Add booster-bitswap request and response count metrics to dashboard

- README.md
- docker/devnet/.env
- docker/devnet/docker-compose.yaml
Fixes for #880.
Change default host dir mapping for fil-proofs from `/var/tmp/filecoin-proof-parameters` to `~/.cache/filecoin-proof-parameters`.
The dir also was made configurable in `.env`.
> Configure docker volume for fil-proofs in .env

- go.mod
- go.sum
- indexprovider/wrapper.go
- node/builder.go
- node/modules/storageminer.go
When booster-bitswap is configured, announce Bitswap as a supported protocol to the indexer
- First, see https://github.com/filecoin-project/go-fil-markets/pull/752 - this updates go-fil-markets to support a custom metadata generation function for a given deal. It also removes treating provider.ErrAlreadyAdvertised as an error when announcing all deals
- In this PR, the indexprovider.Wrapper struct is augmented in the following ways:
- 1. It's configured to run IndexerAnnounceAllDeals once on startup (to catch config updates)
- 2. We no longer treat provider.ErrAlreadyAdvertised as an error when announcing all deals.
- 3. The announcement is augmented on Bitswap if config.DealMaking.BitswapPeerID is set.
- A new constructor function for the legacy storage market provider also configures a …
> Announce Bitswap records to indexer

- cmd/booster-http/server.go
- docker/monitoring/docker-compose.yaml
- docker/monitoring/grafana/dashboards.yaml
- docker/monitoring/grafana/dashboards/exported_dashboard.json
- docker/monitoring/prometheus-remote-write.yaml
Adds a remote write Prometheus configuration to allow for remote writing metrics to a central Prometheus instance.
- Adds `prometheus-remote-write.yaml` configuration file
- Adds host label value of `local` to local `prometheus.yaml` configuration file
- Feature flag for saving Grafana panels to memory
- Updates the Grafana dashboard (a lot of changes have been made)
Before starting prometheus, the `url`, `region`, `access-key` and `secret-key`, and `host` labels in the `docker/monitoring/prometheus-remote-write.yaml` file will need to be updated to use PL Grafana instance and valid credentials for the provider.
The remote write configuration can be used by setting the `PROMETHEUS_CONFIG_FILE` environment variable to `prometheus-remote-write.yaml` upon running `docker compose up -d` on …
> Add prometheus remote write configuration to PL Grafana

- go.mod
- go.sum
Closes: https://github.com/filecoin-project/boost/issues/670
Because CarOffsetWriter got copied into boost, it doesn't need to use the custom branch.
> fix: use tagged go-car release instead of custom branch

- cmd/booster-http/server.go
Fixes https://github.com/filecoin-project/boost/issues/888
> feat: redesign http query url

- extern/boostd-data/couchbase/db.go
- extern/boostd-data/couchbase/db_test.go
- extern/boostd-data/couchbase/service.go
- extern/boostd-data/model/model.go
The size of the multihash -> offset/size map is sometimes too large to fit in a couchbase value (max size 20mb)
So this PR splits the map into shards, and adds a shard prefix to the couchbase key.
> Couchbase record sharding

- cmd/migrate-piecedir/migrate_piece_directory.go
- extern/boostd-data/client/client.go
- extern/boostd-data/couchbase/service.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/svc/svc.go
- extern/boostd-data/svc/svc_test.go
- extern/boostd-data/svc/types/types.go
- piecemeta/mocks/piecemeta.go
- piecemeta/piecemeta.go
Instead of starting up a service.
This should improve performance as calls don't need to go through the RPC interface.
> migrate piece-dir - use direct connection to store

- cmd/boostd/import_data.go
- storagemarket/deal_commp.go
- storagemarket/deal_execution.go
- storagemarket/provider_test.go
fixes https://github.com/filecoin-project/boost/issues/895
> feat: retry offline deal after commp errors

- cmd/booster-http/http_test.go
- cmd/booster-http/server.go
$ curl -v "http://localhost:7777/piece?payloadCid=QmbSLYv6EbbctX5MCuUR6PLxh2sCZLVg5JsUsEMy86tXD2&format=car" --output /tmp/out.car 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:7777...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 7777 (#0)
> GET /piece?payloadCid=QmbSLYv6EbbctX5MCuUR6PLxh2sCZLVg5JsUsEMy86tXD2&format=car HTTP/1.1
> Host: localhost:7777
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Location: /piece/?payloadCid=QmbSLYv6EbbctX5MCuUR6PLxh2sCZLVg5JsUsEMy86tXD2&format=car
< Date: …
> fix: http redirect for /piece/ in booster-http

- cmd/boost/deal_cmd.go
The current help output for `boost deal` gives confusing default value for start-epoch because no Value is specified and the Int type defaults to 0:
```
--start-epoch value          start epoch by when the deal should be proved by provider on-chain (default: 0)
```
This does not explain the mechanics of this flag or what the default behavior actually is. This PR adjusts the output to explain what happens:
```
--start-epoch value          start epoch by when the deal should be proved by provider on-chain (default: current chain head + 2 days)
```
IMO this is still a weird behavior as you are far more likely to want a relative time than absolute epoch value for the deadline, which currently requires making an out-of-band call to either lotus API or a boostd graphQL API to get the chain head …
> Add meaningful default for start-epoch

- Makefile
- README.md
- docker/devnet/.env
- docker/devnet/Dockerfile.source
Solves task (building docker on Mac M1) for https://github.com/filecoin-project/boost/issues/742.
It changes dockerfiles to help build filecoin-ffi from the source:
- adds rust compiled
- allows configuring FFI_BUILD_FROM_SOURCE
The complete solution depends on: https://github.com/filecoin-project/lotus/pull/9363
To build images on mac M1:  `make docker/all ffi_from_source=1`
> Allow building docker from Mac M1

- cmd/booster-http/http_test.go
- cmd/booster-http/server.go
Fixes https://github.com/filecoin-project/boost/issues/966
> feat: introduce http api version

- cmd/booster-http/http_test.go
- cmd/booster-http/mocks/mock_booster_http.go
- cmd/booster-http/run.go
- cmd/booster-http/server.go
- go.mod
Fixes part of https://github.com/filecoin-project/boost/issues/960
> fix: update current http urls as per #960

- gql/resolver_piece.go
- gql/schema.graphql
- react/src/Inspect.css
- react/src/Inspect.js
- react/src/gql.js
Inspect page: search by non-root cid
This is especially useful when debugging retrieval deals where the retrieval deal selector starts from a non-root cid.
> Inspect by non-root cid

- .circleci/config.yml
- extern/boostd-data/couchbase/db.go
- extern/boostd-data/svc/couchbase_test.go
- extern/boostd-data/svc/svc_test.go
Load couchbase from docker and run tests against the dockerized instance.
TODO:
At the moment the [piece directory test is failing](https://app.circleci.com/pipelines/github/filecoin-project/boost/2893/workflows/9bab4a12-2ad1-45b8-a406-fb1cbb18a57e/jobs/26552) because it's trying to connect to couchbase at 127.0.0.1
This works on my local machine but doesn't work on circleci:
```
Error:      	failed to GET http://127.0.0.1:8091/internalSettings after 1m0s: Get "http://127.0.0.1:8091/internalSettings": dial tcp 127.0.0.1:8091: connect: connection refused
```
> Enable couchbase tests with docker

- cmd/migrate-piecedir/main.go
- cmd/migrate-piecedir/migrate_piece_directory.go
Add a Piece Directory reverse migration tool, for the case that SPs need to switch back to a previous version of the boost binary that does not use the Piece Directory.
Essentially the reverse migrate command just copies all deals that were created since switching to the Piece Directory back into the Piece Store.
In order to be able to serve retrievals with these deals, the user will still need to register each new deal with the dagstore manually:
```
$ boostd dagstore register-shard <piece cid>
```
Demonstration of how to do a reverse migration:
```
$ migrate-piecedir reverse couchbase --connect-string='couchbase://127.0.0.1' --username=Administrator --password=password
Performing couchbase reverse migration with logs at reverse-migrate-couchbase.log
Reverse migration complete
$ cat …
```
> Piece Store Reverse migration

- piecedirectory/doctor.go
- piecedirectory/doctor_test.go
Fixes the way that we listen for the context being cancelled in the boost doctor run loop.
TODO:
> exit from piece doctor loop on context cancel

- go.mod
- go.sum
Updates go-data-transfer with a fix for https://github.com/filecoin-project/go-data-transfer/issues/352 which can cause a panic.
> Update data-transfer v1.15.3

- storagemarket/provider_loop.go
Fixes https://github.com/filecoin-project/boost/issues/1047
> fix: run deal filter for offline deals

- gql/resolver.go
- react/src/Mpool.js
Currently when a deal has completed downloading and commp is being verified, the deal status is displayed as "Transferring 100%" or "Deal Queued".
This PR changes the status to "Verifying Commp"
> fix deal status on transfer complete

- cmd/boostx/main.go
- cmd/boostx/sector.go
Adds a new command to boostx to unseal a sector.
Example of unsealing a sector that is already unsealed:
```
$ boostx sector unseal --api-fullnode=$FULLNODE_API_INFO --api-storage=$MINER_API_INFO 1
2023-01-11T16:15:51.740+0100	INFO	boostx	lib/api.go:35	Using full node API at ws://127.0.0.1:1234/rpc/v1
2023-01-11T16:15:51.742+0100	INFO	boostx	lib/api.go:61	Using storage API at ws://127.0.0.1:2345/rpc/v0
2023-01-11T16:15:51.743+0100	INFO	boostx	lib/api.go:103	Miner address: f01000
Sector 1 is already unsealed
```
Example of unsealing a sector that is not yet unsealed:
```
$ boostx sector unseal --api-fullnode=$FULLNODE_API_INFO --api-storage=$MINER_API_INFO 1
2023-01-11T16:16:37.988+0100	INFO	boostx	lib/api.go:35	Using full node API at ws://127.0.0.1:1234/rpc/v1
2023-01-11T16:16:37.989+0100 …
```
> feat: boostx command to unseal a sector

- extern/boostd-data/couchbase/db.go
- extern/boostd-data/ldb/db.go
- extern/boostd-data/ldb/service.go
- piecedirectory/doctor.go
- piecedirectory/doctor_test.go
Fixes https://github.com/filecoin-project/boost/issues/1053
---
This PR is adding a basic implementation of the `NextPiecesToCheck` for the LevelDB adapter.
> implement NextPiecesToCheck for LevelDB

- cmd/booster-http/http_test.go
- cmd/booster-http/run.go
- cmd/booster-http/server.go
I also ran a retrieval on the piece endpoint to make sure that's all still working as expected:
```
$ booster-http run --api-piece-directory="http://localhost:8042" --api-fullnode=$FULLNODE_API_INFO --api-storage=$MINER_API_INFO
2023-01-13T16:29:10.511+0100	INFO	booster	lib/api.go:35	Using full node API at ws://127.0.0.1:1234/rpc/v1
2023-01-13T16:29:10.513+0100	INFO	booster	lib/api.go:61	Using storage API at ws://127.0.0.1:2345/rpc/v0
2023-01-13T16:29:10.514+0100	INFO	booster	lib/api.go:103	Miner address: f01000
2023-01-13T16:29:10.514+0100	INFO	booster	booster-http/run.go:123	Starting booster-http node on port 7777 with base path ''
2023-01-13T16:31:00.280+0100	200	GET /piece/baga6ea4seaqf6bqk7i6t33q2hgg32u3yxdjcipaibaszciyfrto52nocx2cgeii
2023-01-13T16:31:00.280+0100	DONE	GET …
```
> Remove block endpoint from booster-http

- README.md
Removal of the data folder in the docker devnet folder is required between restarts, so just have users always delete it.
> docs: instruct devs to delete data folder for docker

- go.mod
- go.sum
- indexprovider/wrapper.go
Change the logic of advertisement published on startup to cover 3 cases:
1. bitswap is completely disabled: in which case an advertisement is published with empty extended providers that should wipe previous support on indexer side.
2. bitswap is enabled with public addresses: in which case publish an advertisement with extended providers records corresponding to the public addresses. Note, according the the IPNI spec, the host ID will also be added to the extended providers for signing reasons with empty metadata making a total of 2 extended provider records.
3. bitswap  is enabled with boostd address: in which case public an advertisement with one extended provider record that just adds bitswap metadata.
Note that in any case one advertisement is published by boost on startup to reflect …
> Upgrade to the latest index provider with fixes to bitswap retrieval ads

- cmd/boostd/main.go
- node/builder.go
This makes it easier to diagnose issues with dependency injection (eg if it takes a long time for boostd to startup).
Enable fx logging by running boostd in very verbose mode:
```
boostd run --vv
```
> Add option to output fx dependency injection log on startup

- gql/resolver_piece.go
- react/src/Inspect.js
- react/src/gql.js
At the moment the Inspect page is slow to load, because for each flagged piece we synchronously check if the piece is unsealed.
This PR changes the front end code so that it checks the unsealed status of the piece asynchronously, after the page has loaded. It also changes the resolver so that the unsealed status of the piece is only checked if requested as part of the list query.
> load unseal status of flagged pieces asynchronously

- react/package-lock.json
- react/package.json
This swaps over the graphql websocket dependency as described at https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws.
I've verified the front end now builds on node 16.x, 18.x, and 19.4, running against my local boost instance.
fixes https://github.com/filecoin-project/boost/issues/753
> fix: update deps to support node 16 and 18

- cmd/booster-bitswap/init.go
When adding a connection between boostd and booster-bitswap, the Storage Provider needs to configure the peer ID and the path to the key file.
This PR modifies the `booster-bitswap init` command to also output the key file path.
```
$ booster-bitswap init
Initialized booster-bitswap with libp2p peer ID 12D3KooWSP1SwCpRzgW8WZPty4T6dZJfWKjqsp2tntxBtDCmQbHf
Key file: /home/user/.booster-bitswap/libp2p.key
```
> booster-bitswap init: output keyfile path

- cli/util/verbose.go
- cmd/booster-bitswap/init.go
- cmd/booster-bitswap/main.go
- cmd/booster-bitswap/remoteblockstore/remoteblockstore.go
There are now three modes:
- Normal:
Just output startup message with booster-bitswap listen address
- Verbose `-v`
Output a message for each block served
- Very verbose `-vv`
Output a message for each request received (has, get size, get block)
The `-v` flag was being used to output the version. So instead I added a `version` command so we can use `-v` for Verbose mode.
```
$ booster-bitswap version
booster-bitswap 1.5.1-rc3+git.b31dbff.dirty
$ booster-bitswap -v run --api-boost=$BOOST_API_INFO
2023-01-24T11:51:36.977+0100	INFO	booster	booster-bitswap/run.go:187	Using boost API at ws://127.0.0.1:1288/rpc/v0
2023-01-24T11:51:37.015+0100	INFO	booster	booster-bitswap/run.go:145	Starting booster-bitswap node on port 8888
2023-01-24T11:51:37.016+0100	INFO	booster	booster-bitswap/server.go:82 …
```
> Adjust booster-bitswap verbosity

- cmd/booster-bitswap/remoteblockstore/remoteblockstore.go
- docker/monitoring/grafana/dashboards/provider-retrievals.json
- metrics/metrics.go
Adds a "Bytes Served" dashboard in grafana
> Add bitswap bytes served grafana dashboard

- docker/monitoring/docker-compose.yaml
- docker/monitoring/tempo-local.yaml
The new version seems to wait no more than 10s for tempo to shutdown:
```
^C
Gracefully stopping... (press Ctrl+C again to force)
[+] Running 4/4
⠿ Container loki        Stopped  0.6s
⠿ Container prometheus  Stopped  0.6s
⠿ Container tempo       Stopped  10.2s
⠿ Container grafana     Stopped  0.6s
canceled
```
> update tempo version

- cmd/migrate-lid/migrate_lid.go
- extern/boostd-data/client/client.go
- extern/boostd-data/couchbase/db.go
- extern/boostd-data/couchbase/service.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/model/model.go
- extern/boostd-data/svc/svc_test.go
- extern/boostd-data/svc/types/types.go
- node/impl/boost.go
- piecedirectory/doctor_test.go
- piecedirectory/piecedirectory.go
- piecedirectory/piecedirectory_test.go
- piecedirectory/types/mocks/piecedirectory.go
- piecedirectory/types/types.go
Adds a `CompleteIndex` flag to the local index directory model to indicate whether the index is complete, or missing block size information (because it was imported from the dagstore)
> handle blockstore GetSize for indexes imported from the dagstore

- .github/workflows/main.yml
Resolves the failed project board assignment workflows - https://github.com/filecoin-project/boost/actions/workflows/main.yml.
ProjectNext was [deprecated](https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/) and is now projectv2. This updates the workflows to use the new apis. This was already completed on the docs repo https://github.com/filecoin-project/boost-docs/pull/28
> fix: remove usage of deprecated projectnext api

- car/car_offset_writer_test.go
- go.mod
- itests/dummydeal_offline_test.go
- itests/dummydeal_test.go
- itests/framework/framework.go
- testutil/car.go
- transport/httptransport/http_transport_test.go
Any CAR file with an identity CID as the root payload CID is unretrievable if written with CarV2.
When a file is imported via UnixFS, the default builders have a condition where any block less than 126 bytes becomes an identity CID. This is true for the [most common CAR generation utils used by Lotus & boostx](https://github.com/filecoin-project/lotus/tree/master/lib/unixfs). So this is likely applicable to real world pieces.
Car files written with CarV1 with identity CIDs may or may not be retrievable but as they are written back out with CarV2 writers they likely won't match commP if trying to do whole payload / piece retrieval over GraphSync.
This PR is actually an issue with a test to demonstrate. This issue affacts the default integration tests, and you can demonstrate simply by …
> Failure to retrieve when root payload CID is an identity CID

- gql/resolver_piece.go
- gql/schema.graphql
Adds the ability to query graphql for all the indexes in a piece. This is particularly useful for doing index integrity checks, but I am also aiming to use this for retrieval testing of sub piece data. (ie: Random retrieval sampling of indexes for a given piece)
```bash
curl -s -X POST http://localhost:8080/graphql/query -d '{"query":"{\n  pieceIndexes(pieceCid: \"baga6ea4seaqnu565elcclgmhv7nvypneacwjq3t4ahudduqyhrvdsdtu6jjamjq\")\n}"}' | jq
{
"data": {
"pieceIndexes": [
"bafykbzaceathxr6h7abpsv7d4vretuip4ofra7yncqaq6j5v5qaarhvg74jtg",
"bafykbzacebaymiuvntyrgwkxykwvhclbjs2n5tegc4zpfwwzuoeezh3bnzkvw",
"bafykbzacebgtrrb3xs6bqudhdkpogbtt5ztzdgj6asmhnpze5x6izxrjv6k4k",
"bafykbzacebs4o2gdi32n4pmhkzaiqojo242wrw5tlwk6g3trbl767o22bvsy2", …
```
> Add gql endpoint for returning all indexes for a given piece cid

- cli/node/node.go
- cmd/boost/retrieve_cmd.go
Change the `boost retrieve` command to use a temporary blockstore and datastore instead of using the ones in the boost client repo.
```
$ ./boost retrieve --output="/tmp/out.dat" --provider=f0127896 QmZaiSRWGZNqTtmZqPQvDydcipMDQsotmR5zKnPvMvjRdL
RETRIEVAL STATS (FIL)                                                                                                                     
-----
Size:          6538485 (6.2 MiB)
Duration:      1.436920372s
Average Speed: 4550346 (4.3 MiB/s)
Ask Price:     0 (0 FIL)
Total Payment: 0 (0 FIL)
Num Payments:  0
Peer:          12D3KooWE8yt84RVwW3sFcd6WMjbUdWrZer2YtT4dmtj3dHdahSZ
Saved output to /tmp/out.dat
```
> use temporary blockstore and datastore for retrieve command

- cmd/booster-bitswap/run.go
- cmd/booster-http/run.go
- node/modules/piecedirectory.go
- piecedirectory/piecedirectory.go
- piecedirectory/piecedirectory_test.go
- storagemarket/provider_test.go
When an index is imported from the dagstore, it does not have block size information.
When a bitswap request comes in, and the local index directory notices that the index for the corresponding piece is incomplete, the local index directory starts a new add index operation (to rebuild the index).
Add index operations are put into a queue. Once the add index operation starts, we don't want to cancel it if one of the threads waiting on the operation cancels its context. So instead of using the waiting thread context, use the local index directory's context.
> use long running context for add index operations

- .circleci/config.yml
The mac build was previously only running on tagged releases, while this saves CI compute resources it also made it difficult to catch and resolve build failures. 
You can see the previous failure on the most recent RC - https://app.circleci.com/pipelines/github/filecoin-project/boost/3188/workflows/c7bb14a1-2ca6-45ca-ab9c-852325de014a/jobs/30322.
* Macos builds will now be triggered for any branch starting with `ci/`, in addition to running on tags
* Fixed the golang runtime to use amd, it was using arm which isn't supported on circle
* Increased the resource class of the build as it's currently in plan and resulted in a 17% reduction in build time. This does not run frequently so the credit burn impact should be negligible.
> chore(ci): fix macos build

- piecedirectory/piecedirectory.go
- piecedirectory/types/types.go
When a client makes a request for data, the local index directory gets a reader over the data from the sealing subsystem.
If the data is not unsealed, just return an error.
> Don't unseal sectors in local index directory

- go.mod
- go.sum
- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/storageminer.go
This switches over the dagstore index backed blockstore to use an expiry based LRU cache instead of just an LRU. The existing LRU will never prune unless it fills up and evicts. With the new cache, expired entries will automatically be removed, and in the event the cache hits its max size, the shards closest to expiry will be pruned first.
* Adds a config option, `DealmakingConfig.BlockstoreCacheMaxShards` to set the max shards in the cache. The previous value was hard coded at `100`, which the default has been set to, but we may want to lower this as it can cause process memory to grow quite large. Too low can cause in progress retrievals to fail as shards in use can be pruned.
* EDIT: reduced to `20` to match default simultaneous retrieval limits
* Adds a config option, …
> feat: use an expiry lru cache for the index backed blockstore

- itests/framework/framework.go
- node/config/doc_gen.go
- node/modules/storageminer.go
- storagemarket/lp2pimpl/net.go
- storagemarket/provider.go
- storagemarket/provider_test.go
This means that whether ExecuteDeal is called from libp2p or from a chain event listener, it will still log the accept / reject status in a way that it will show up in the UI
> Move deal accept / reject logging to be part of deal execution

- README.md
- cmd/boostx/main.go
- cmd/boostx/utils_cmd.go
- docker/devnet/boost/sample/random-deal.sh
- docker/devnet/docker-compose.yaml
- testutil/car.go
This PR contains a few dev utilities that I'm bundling together as a followup of doing retrieval testing of booster-bitswap
* [364367e](https://github.com/filecoin-project/boost/pull/1143/commits/364367e9c9fed458ec99975c49de2186d1afaf41) adds traffic control to the docker setup. It also adds a small latency to bitswap and http retrievals which mimics a reasonable local region latency of 10ms. The demo http server also now has a rate limited 1m connection and 100ms latency. This is probably excessive, but should also make it easier to test transfer components. This TC setup also has support for things like corrupted packets, but I've skipped including that for now.
* [b9653ae](https://github.com/filecoin-project/boost/pull/1143/commits/b9653ae9d6d266b0a76a3a25a87e9bbcd1bca290) adds a …
> test: add utilities and improvements for local testing

- cmd/booster-bitswap/run.go
- cmd/booster-bitswap/server.go
- docker/devnet/booster-bitswap/entrypoint.sh
This PR adds several flags to the `booster-bitswap run` command to set internal parameters on the bitswap server, https://github.com/ipfs/kubo/blob/master/docs/config.md#internalbitswap. The bitswap worked defaults are considerably low, 8, so we are also bumping the defaults here as even small scale SP's will have significantly more hardware than the defaults for bitswap were intended to support.
These are currently added as flags to the process as we don't yet have a dedicated config for booster-bitswap. We should consider whether we want to add and migrate to that in the near future, but I'm leaving that out of the scope for this PR for now as we're targeting a release this week. If we want to go that route, I'll create an issue to track adding the config in a future update.
``` …
```
> feat: add flags for bitswap server internals

- node/modules/storageminer.go
- storagemarket/deal_acceptance.go
- storagemarket/provider_test.go
- storagemarket/types/types.go
This code is ported from https://github.com/filecoin-project/lotus/blob/ef3b2046b6765bb76517563cc3957a595621bf9f/markets/storageadapter/client.go#L98
Questions:
> verify deal proposal for f4 address

- storagemarket/deal_execution.go
- storagemarket/lp2pimpl/net.go
- storagemarket/lp2pimpl/net_test.go
- storagemarket/provider_test.go
- storagemarket/smtestutil/mocks.go
- storagemarket/types/legacy.go
- storagemarket/types/types.go
- storagemarket/types/types_cbor_gen.go
Fixes #1184
The new deal proposal protocol supports two extra fields as described in
https://github.com/filecoin-project/FIPs/blob/f30244781db571d3b0420f414be28e6d84cfa1f9/FRCs/frc-0056.md
> Introduce deal proposal protocol v1.2.1

- Makefile
- README.md
- docker/devnet/.env
Implemented as requested in  (#1084).
Now building images the first time for devnet should be twice faster.
- tested with an official lotus image: [v1.19.0-debug](https://hub.docker.com/layers/filecoin/lotus-all-in-one/v1.19.0-debug/images/sha256-295f057ad0fbae829b168592d486c91e801bcf053e9be95f217869acbb5b8d44?context=explore). The image works out of the box, without any other changes
- updated Makefile to use the official lotus docker image instead of building locally as the default case
- ~~refactored makefile to use a new lotus dockerfile~~, but rollbacked. The tag 1.19.0 (default now) of the lotus repo does not contain the new Dockerfile, so the building did not work out-of-the-box
- updated readme
Works only for amd64 platforms
```bash
make docker/all
make docker/all …
```
> Devnet images using Lotus from DockerHub

- markets/idxprov/mesh.go
Currently, index-provider requires full node to be publicly exposed. AFAIK, no other lotus-miner module has thing requirement and this becomes another security concern.
If the libp2p address is not reachable we get the below error. This behaviour is consistent on Boost as well.
failed to connect index provider host with the full node: failed to connect index provider host with the full node: failed to dial 12D3KooWJgxyYahRiJ6rHUJPeigWoXJ8SwFKNKHSxXje1D1BvGVR:
* [/ip4/76.219.232.45/tcp/24002] dial tcp4 76.219.232.45:24002: connect: connection refused
waiting for legacy storage provider 'ready' event 
We need to change the direction of libp2p connection init. Rather than dialling from market to fullNode, we should dial from fullNode to market. Thus removing the requirement to have libp2p …
> Port https://github.com/filecoin-project/lotus/pull/9627 to Boost

- docker/devnet/boost/entrypoint.sh
This workaround is ported from https://github.com/filecoin-project/boost/pull/573.
The recent merged updates for the base LID code base causes boost to fail to startup in docker. This manually creates the deal-staging directory to resolve the issue until it's properly fixed in the LID line of development.
> chore(fix): port docker workaround from lid branch

- node/modules/dealfilter.go
- storagemarket/provider_dealfilter.go
Fixes https://github.com/filecoin-project/boost/issues/1208
This PR also extend the deal params exposed to the external deal filters like CIDGravity. Before this an offline deal was sending a false value for IsOffline to external filter.
> fix: BasicDealFilter logic

- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/storageminer.go
- storagemarket/provider.go
- storagemarket/provider_dealfilter.go
- storagemarket/provider_loop.go
- storagemarket/provider_test.go
Fixes https://github.com/filecoin-project/boost/issues/1207
Suggested design by DIrk:
if there is no deal filter enabled in config, don't call the method at all
if the deal filter is enabled
> check the cache
> if the cache is empty
> > call the method
> > store the results in the cache
>> expire the result after x time (where x is configurable)
> return the result
> feat: cache sealing pipeline status

- storagemarket/provider_dealfilter.go
- storagemarket/provider_loop.go
Basic filters are now working as expected.
Online = false and offline = true
online = true and offline = false
> fix: bug bypassing basic filters

- storagemarket/provider_dealfilter.go
- storagemarket/provider_loop.go
* fix bug bypassing basic filters
* update code comments
> fix: backport 1217 to release/v1.5.x

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/enhancement_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- node/config/doc_gen.go
When we were launching Boost, it was decided that we will entertain feature/enhancement requests only via discussion. After multiple iterations, we have seen that requests coming in have been reasonable and useful.
If everyone in the team agrees, I would like to enable direct filing of feature requests and enhancement requests at this point. I will also update the docs to point to these templates.
> chore: enable feature and enhancement report

- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/retrieval.go
- retrievalmarket/rtvllog/db.go
- retrievalmarket/rtvllog/retrieval_log.go
As part of debugging https://github.com/filecoin-project/boost/issues/1125 we determined that stalled retrievals were never being cleaned up by the go-fil-markets code. This was originally intended to allow resumption of retrieval, however, there was never a cap put on the duration and retrievals would require manual termination. This behavior doesn't scale.
There is refactoring that is needed for the go-fil-markets retrieval codepaths as a separate effort, but in the interim, this will provide a short term fix for canceling stalled retrieval.
This new job runs every 5 minutes and will cancel all retrievals in the Retrieval Log that have not been updated in the past 30 minutes (configurable). 30 minutes should be a reasonable default for clients to attempt to reconnect and resume transfer …
> feat: add job to cancel stalled retrievals

- cmd/boost/retrieve_cmd.go
This caused some confusion when I tried using boost cli to retrieve a piece cid: https://filecoinproject.slack.com/archives/C03CKDLEWG1/p1677594315263249
> clarify cid type

- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/retrieval.go
- retrievalmarket/rtvllog/db.go
- retrievalmarket/rtvllog/retrieval_log.go
This back ports the retrieval cancel job from https://github.com/filecoin-project/boost/pull/1233 to the v1.5.x release line. 
Please see that PR for details.
> feat: back port add job to cancel stalled retrievals (#1233)

- Makefile
- README.md
- drop excess parameter `lotus_checkout_dir`, use `lotus_src_dir`.
- drop if clause `ifeq ($(lotus_src_dir),)` ...
- use the new lotus `Dockerfile` instead of the old one `Dockerfile.lotus` when building lotus from source
> Simplify docker build tasks

- Makefile
- README.md
> fix docker image tagging

- react/src/Components.js
Fixes https://github.com/filecoin-project/boost/issues/1238
Instead of displaying the common characters in a Peer ID, this will display the end of the PeerId. This makes it easier to quickly discern requests from different peers.
You can see in the screenshots below of the exact same data that while the PeerIDs all look the same before, showing the last 8 characters instead of the first 8 clearly shows they're all unique peers.
**Before**
**After**
> feat(ui): display end of peerid instead of front

- node/impl/boost.go
- node/impl/boost_legacy.go
- retrievalmarket/server/channelstate.go
- retrievalmarket/server/gsunpaidretrieval.go
- retrievalmarket/server/gsunpaidretrieval_test.go
This hooks up the GraphsyncUnpaidRetrieval server to the cli for managing data-transfers.
- `boostd retrieval-deals list` will currently not show GSUnpaidRetrievals that have completed(error or success) as they are no longer tracked. The records only exist in the retrieval log. Deals made with the old code path will continue to show in this list regardless of status.
```
$ boostd retrieval-deals list
Receiver                                              DealID               Payload      State               PricePerByte  BytesSent  Message
12D3KooWQqsi3sKKW6rbxgmH5MAuvvYi6LiCaxTKT7u4GMu3Qq1H  1678278198331351001  ...hgh7h452  DealStatusNew       0             0          
12D3KooWCUyu21tPs3Yzftfb4uzviYmACLyr9pxUVaB8cNGUJBvV  1678278198331388001  ...vhlvr5f2  DealStatusUnsealed  0 …
```
> feat: hook up unpaid gs retrievals to cli

- .circleci/config.yml
Mac medium and large resources are being deprecated so updating this now, https://discuss.circleci.com/t/macos-resource-deprecation-update/46891. The new large resource is available as an m1, but the runtime cost is 4x the current large, https://circleci.com/product/features/resource-classes/#macos, so moving this back to medium for the time being.
The current go install doesn't work on xcode 14 for some reason I haven't looked into, so postponing updating that for now.
> chore(ci): update deprecated mac resources

- transport/httptransport/http_transport.go
Fixes https://github.com/filecoin-project/boost/issues/1283
> Dont log errors when the transfer event queue is full

- storagemarket/deal_execution.go
- storagemarket/provider_test.go
Fixes: https://github.com/filecoin-project/boost/issues/1286
> fatally fail contract deals on publish errors

- storagemarket/contract_deal_monitor.go
It appears we are receiving some events twice from Lotus, so it would be helpful to log the actual deal id we get from the chain, alongside the client contract address.
> better logs for deal id

- go.mod
- go.sum
Once Lotus releases the 1.21.0-rc we can get off of these boost tags of lotus with the index provider commit fixes applied. For now this upgrades to the latest 1.20.3 release with the commits applied.
fixes https://github.com/filecoin-project/lotus/issues/10482
This has been deployed and testing on 2 production SP's.
TODO:
> chore: update lotus and jsonrpc

- go.mod
- go.sum
- storagemarket/deal_handler.go
- storagemarket/newdealps.go
https://github.com/filecoin-project/boost/issues/1303
github.com/libp2p/go-eventbus is deprecated and should boost should be using github.com/libp2p/go-libp2p/p2p/host/eventbus instead.
this helps with removing references to `go-libp2p-core` in dependencies:
```
> go mod graph | grep libp2p-core
....
github.com/libp2p/go-eventbus@v0.2.1 github.com/libp2p/go-libp2p-core@v0.5.7
....
```
> removing libp2p-go-eventbus

- node/builder.go
- node/modules/lp2p.go
TODO:
```
$ boost provider libp2p-info t01000
Provider: t01000
Agent: boost-1.6.1-rc1
...
````
> Set user agent from boost build version instead of lotus

- cmd/boostx/stats_cmd.go
Fixes https://github.com/filecoin-project/boost/issues/1271
```
Total Boost nodes: 17
Total Boost raw power: 20588664467750912
Total Boost quality adj power: 164240643386998784
Total Lotus Markets nodes: 40
Total SPs with minimum power:  3603
Total Indexer nodes: 43
Agent Versions:
lotus-1.18.0+mainnet: 1
lotus-1.18.2+mainnet: 1
lotus-1.20.0+mainnet: 2
lotus-1.20.0-rc1+mainnet: 2
lotus-1.20.0-rc2+debug: 1
lotus-1.20.0-rc2+mainnet: 8
lotus-1.20.6+mainnet: 2
Retrieval Protocol Support:
bitswap: 1
libp2p: 17
```
Unfortunately it seems that the UserAgent is being set to the lotus version imported by boost (not boost's build version).
This is because we build the Host using lotus modules rather than building it from boost modules:
https://github.com/filecoin-project/boost/blob/f3622c8e803924c5a …
> boostx stats: output agent version and retrieval protocols

- go.mod
- go.sum
- retrievalmarket/server/gsunpaidretrieval_test.go
To fix these kinds of retrieval errors:
```
ERROR   gs-queryexecutor        queryexecutor/queryexecutor.go:190      traversal completion check failed, nBlocksRead=1, err=unregistered adl requested: "unixfs-preload"
```
`unixfs-preload` was added a year ago in go-unixfsnode - it allows us to write a selector that will go right up to a whole sharded file or a whole sharded directory, not just the root block of the shard, and not into a sharded directory (i.e. for a sharded directory it gives you enough to do an `ls` on the directory but none of the contents. A `unixfs` ADL that doesn't explore-all underneath the shard would just match the root.
It was added in go-unixfsnode@v1.5.1: https://github.com/ipfs/go-unixfsnode/releases/tag/v1.5.1
Unfortunately, if we update go-unixfsnode later than …
> fix: update go-unixfsnode enough to make sure unixfs-preload is available

- retrievalmarket/rtvllog/db.go
- retrievalmarket/rtvllog/retrieval_log.go
Fixes https://github.com/filecoin-project/boost/issues/1326
Unfortunately, it doesn't look pretty when we have long error strings. But it works as expected. We are now seeing failed queries.
> feat: query UI

- Makefile
- docker/devnet/.env-stable
- docker/devnet/Dockerfile.source
The devnet build was breaking after https://github.com/filecoin-project/boost/pull/1333, this PR just bumps to golang 1.19 to stay inline with the golang version in boost go.mod.
* Also bump default lotus to latest v1.21 rc
* Removes the unused and outdated .env-stable file for devnet
> fix(devnet): update golang and lotus default versions

- react/src/Inspect.js
This fixes the rendered HTML to use the correct root cid block, when the root cid is show on the inspect page. Previously whatever the search query was (piece cid, root cid, or payload cid) would be used.
Screenshot of the correct html, you can see the label and cid url match
> fix: correct link for download root block

- cmd/boostx/stats_cmd.go
- cmd/boostx/stats_cmd_test.go
Fixes https://github.com/filecoin-project/boost/issues/1361
```
$ ./boostx stats --sp-query-concurrency=10 --sp-query-max=500
...
Total Boost nodes: 43
Total Boost raw power: 99173234406064128
Total Boost quality adj power: 435450019682222080
Total Lotus Markets nodes: 69
Total SPs with minimum power:  3542
Total Indexer nodes: 96
Agent Versions:
boost-1.6.1: 3
boost-1.6.2-rc2: 1
lotus-1.17.2-dev+mainnet: 4
...
lotus-1.20.6: 1
lotus-1.21.0-rc2+mainnet: 2
lotus-lianjing-kwj 1.20.0+mainnet: 1
venus-marketv2.5.0: 1
venus-marketv2.6.0: 6
Retrieval Protocol Support:
bitswap: 3
http: 2
libp2p: 43
```
> group agent version by binary name

- storagemarket/deal_execution.go
- storagemarket/provider.go
- storagemarket/provider_test.go
Fixes https://github.com/filecoin-project/boost/issues/1277 partially as we are failing deals during start up and when deal execution process starts.
> feat: fail deal if start epoch passed

- .gitignore
- Makefile
- docker/devnet/Dockerfile.source
- docker/devnet/boost/entrypoint.sh
- docker/devnet/booster-bitswap/entrypoint.sh
- docker/devnet/booster-http/entrypoint.sh
- docker/devnet/docker-compose.yaml
- extern/boostd-data/cmd/run.go
- extern/boostd-data/couchbase/db.go
- extern/boostd-data/couchbase/service.go
- extern/boostd-data/ldb/db.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/svc/setup_couchbase_test_util.go
- extern/boostd-data/svc/svc.go
- extern/boostd-data/svc/svc_test.go
- node/modules/piecedirectory.go
- piecedirectory/doctor_test.go
- piecedirectory/piecedirectory_test.go
This PR updates docker devnet in the LID (local index directory) branch so that booster-http and booster-bitswap are once again able to run.
_Note_: No changes have been made to the boostd api itself, the only change is in the boostd-data service mentioned below.
* BREAKING CHANGE: The boostd-data service now takes an `--addr` flag instead of `--port`, so that it can be bound to non localhost IP addresses. This is needed for cross container communication, and may be useful in larger scale deployments. - [919cb57](https://github.com/filecoin-project/boost/pull/1375/commits/919cb578b752017dd16f941e7c127367af6d22f8)
* Fixed linting in extern/boostd-data. We currently aren't linting the "sub project" in CI so linting was failing here. I separate this as it's own commit …
> fix: make devnet work for lid

- indexprovider/unsealedstatemanager.go
- indexprovider/unsealedstatemanager_test.go
- indexprovider/wrapper.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
Adds to https://github.com/filecoin-project/boost/pull/1191 to call storage redeclare on the lotus-miner. Lotus doesn't currently automatically detect fs changes, so this is needed to ensure we're able to automatically keep indexes and their metadata up to date.
Speaking with the Lotus team, this call should be cheap so running it regularly shouldn't be an issue.
This is a screenshot of the before and after `lotus-miner storage list`. On the left the list shows 2 of 4 sectors as being unsealed, but we can see by the screenshot that there is only 1 unsealed sector. After the logs of the job execute (on the right), the storage list then correctly shows 1 of 4 sectors as unsealed.
It may be useful to allow configuring how often the unseal manager is run. Currently it runs every hour, but in …
> feat: redeclare storage when unsealed state is checked

- node/config/doc_gen.go
Main and the 1.7.2 were off and the previous PR didnt catch that. This resolves the current discrepancy on main.
> chore: fix docsgen on main

- gql/resolver_mpool.go
Fixes below panic:
```
2023/05/01 10:57:52 graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference
goroutine 5624764 [running]:
github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0x9249208?, {0x6a14b08?, 0xc0206470e0}, {0x517fde0, 0x8e50930})
/home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/log/log.go:21 +0x65
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1()
/home/nonsense/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:187 +0x89
panic({0x517fde0, 0x8e50930})
/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/filecoin-project/boost/gql.(*resolver).Mpool(0xc0009141e0, {0x6a14b08, 0xc0206471a0}, {0x39?})
/home/nonsense/boost/gql/resolver_mpool.go:70 +0x496 …
```
> fix: mpool all messages panic

- docker/devnet/booster-http/entrypoint.sh
For ease of devnet testing, this just updates the booster-http entrypoint to also include the `--serve-files=true` flag to enable the files view of the IPFS gateway, which is disabled by default.
> chore: enable files gateway in devnet by default

- cmd/boost/deal_cmd.go
I was confused about something here for “offline” deals.
[car-size is a required parameter](https://github.com/filecoin-project/boost/blob/main/cmd/boost/deal_cmd.go#L50)
[which is not allowed to be zero](https://github.com/filecoin-project/boost/blob/main/cmd/boost/deal_cmd.go#L196-L199)
but [transfer](https://github.com/filecoin-project/boost/blob/main/cmd/boost/deal_cmd.go#L200) is zeroed out for offline deals.
This PR means car-size is no longer checked unless it's an online deal.
> car size required only for online deals

- indexprovider/unsealedstatemanager.go
- indexprovider/wrapper.go
Currently we announce a deal from two places:
- when a new storage deal is created, it gets indexed and announced
- when a deal is unsealed, it gets announced
In the case where the deal is unsealed, and there is an error, we ignore the error if it's because the deal has already been announced.
This change ensures that we also ignore the "already announced" error when a new deal is indexed and announced.
> Dont throw error if deal already announced

- go.mod
- go.sum
Updates go-commp-utils lib to v0.1.4
Fixes https://github.com/filecoin-project/boost/issues/1358
> fix: 64 GiB local commp

- node/builder.go
- node/modules/piecedirectory.go
Resolves a panic when the user clicks on Download Block on the Inspect page (only occurs on the LID branch)
> Fix block download

- retrievalmarket/server/channelstate.go
- retrievalmarket/server/gsunpaidretrieval.go
- retrievalmarket/server/gsunpaidretrieval_test.go
While I can't determine definitively if this is the root cause of the retrievals getting stuck, I can say with some assurance that the problem this PR aims to fix will in most cases prevent your automatic retrieval canceller from actually working.
In the unpaid retrieval code, when CancelTransfer is called, while a message is sent to the client that the data transfer should be cancelled, the actual GraphSync request is not cancelled. If the client successfully receives the message AND their code is setup as it should be, they will cancel the GraphSync request based on the message. However, that's a big if, especially in the case of unresponsive data transfers where one can probably assume the client is no longer reachable. The proper behavior is to have the server immediately cancel the …
> Properly cancel graphsync requests in unpaid retrieval

- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
We should avoid setting it to 0.0.0.0 by default as SPs might end up exposing their UI to the internet if firewall is not configured properly.
I have just come across one such instance. Better safe than sorry.
We also need to update our V2 docs with much more detail about networking and security.
> fix: set UI default listen address to localhost

- gql/resolver_mpool.go
- react/src/Mpool.css
- react/src/Mpool.js
Possible nil pointer error from incorrect type
> feat: display msg params in the mpool UI

- go.mod
- storagemarket/lp2pimpl/net.go
Fixes https://github.com/filecoin-project/boost/issues/1478
Also adds some more detailed logging to help track down slow parts of the code in future (at the debug level):
```
2023-05-31T09:40:29.458+0200	DEBUG	boost-net	lp2pimpl/net.go:204	new deal proposal request
{"reqlog-uuid": "d2f985bc-fe38-4f90-9ddf-a46c123e55d4", "client-peer": "12D3KooWMkmxGo988mtZWeNoUZD4mJpmeLym1P962bRNLDF6qX8D"}
2023-05-31T09:40:29.458+0200	INFO	boost-net	lp2pimpl/net.go:223	received deal proposal
{"reqlog-uuid": "d2f985bc-fe38-4f90-9ddf-a46c123e55d4", "client-peer": "12D3KooWMkmxGo988mtZWeNoUZD4mJpmeLym1P962bRNLDF6qX8D", "id": "9bda7d00-100e-427e-a24e-88d1fd48ce00"}
2023-05-31T09:40:29.465+0200	DEBUG	boost-net	lp2pimpl/net.go:230	processed deal proposal accept
{"reqlog-uuid": …
```
> Reset read deadline after reading deal proposal message

- docker/devnet/boost/entrypoint.sh
- docker/devnet/docker-compose.yaml
- gql/resolver.go
> feat: Show elapsed epoch and PSD wait epochs in UI

- storagemarket/deal_execution.go
```
2023-06-05T15:15:20.168+0200    ERROR   boost-provider  storagemarket/deal_execution.go:86      caught panic executing deal     {"id": "51734ff6-62ca-4180-9969-f793d863d593", "err": "something went wrong"}
goroutine 1123 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/filecoin-project/boost/storagemarket.(*Provider).execDeal.func1()
/Users/dirk/go/src/github.com/filecoin-project/boost/storagemarket/deal_execution.go:87 +0x1a8
panic({0x1073db1e0, 0x107a76840})
/usr/local/go/src/runtime/panic.go:890 +0x26c
github.com/filecoin-project/boost/storagemarket.(*Provider).execDeal(0x1400c67afc0, 0x1400ca7c380, 0x1400090e8c0)
/Users/dirk/go/src/github.com/filecoin-project/boost/storagemarket/deal_execution.go:95 +0x90 …
```
> log panic (instead of just printing to stdout)

- node/modules/piecedirectory.go
- piecedirectory/doctor.go
- piecedirectory/doctor_test.go
- sectorstatemgr/sectorstatemgr_test.go
The algorithm in `checkPiece` currently flags piececids that the SP never stored -- they submitted a PSD, but the deal was never added to a sector. Even worse, another deal later on got added to that particular sectorID, which means that based on the metadata in LID, we would "think" that the deal's sector is `active`.
Therefore I am changing the algorithm to:
1. Check if piece belongs to an active sector
2. For the active sectors / deals from 1, check that at least one deal is actually found on-chain
3. At this stage we know there is an active sector and a real ChainDealID; check if the piececid is indexed
4. If the piece is indexed and has active sector and active deal on chain, check for unsealed copy
We `Flag` a piece on step 3 and 4 if a piece is not indexed or if there is no …
> piece doctor to ignore expired/slashed deals

- react/src/LID.js
This PR is disabling `block stats` and `deal data` so that we pass LID to testers as soon as possible, given that these 2 panels are not super critical.
> disable dummy panels - block stats; deal data

- react/src/Info.css
- react/src/LID.js
> Add info boxes on LID UI page

- cmd/migrate-lid/main.go
- cmd/migrate-lid/migrate_lid.go
Fixes https://github.com/filecoin-project/boost/issues/1514
> Replace migrate couchbase command with migrate yugabyte

- gql/resolver_mpool.go
- gql/schema.graphql
- react/src/App.js
- react/src/MonitoringAlert.css
- react/src/MonitoringAlert.js
- react/src/Mpool.js
- react/src/gql.js
> Add monitoring alert UI element

- gql/resolver.go
- gql/resolver_legacy.go
- gql/resolver_piece.go
- gql/resolver_sealingpipeline.go
- gql/schema.graphql
- lib/legacy/dealmanager.go
- node/builder.go
- node/modules/storageminer.go
- react/src/LID.js
- react/src/gql.js
The list of flagged pieces is quite slow to load. This is because it scans through all the legacy deals to find matches against flagged pieces.
This PR adds an index for legacy deals by piece cid, root payload cid and publish cid. The index is refreshed every 10 minutes.
Test:
> Build indexes for legacy deals

- gql/resolver_mpool.go
- gql/schema.graphql
- lib/mpoolmonitor/mpoolmonitor.go
- react/src/MonitoringAlert.js
- react/src/Mpool.js
- react/src/gql.js
This PR fixes https://github.com/filecoin-project/boost/issues/1526  and introduces the following changes to the Mpool page in UI.
1. It removed the all messages
2. Only local messages are captured by mpoolMonitor
3. Mpool resolver now works for alert messages or all messages
4. By default mpool UI will show all alert messages in details. This would allow for better debugging than just saying how many messages are stuck.
5. The button had been updated to show all local messages. User will have less use of local messages as well if there are not alerts. Thus the decision to make alerts primary and all messages a secondary query.
> feat: refactor mpool page in UI

- node/config/migrate.go
- node/config/v4_to_v5.go
> migrate config to v5

- cmd/boost/provider_cmd_test.go
- node/modules/retrieval.go
Fixed #1555 
Output with Public Bitswap address:
```
libp2p
/ip4/127.0.0.1/tcp/50000/p2p/12D3KooWQwgwg4FwN1SDxXvuQkYRtuDsW7ysgHtqsZyfYv1nurQj
/ip4/172.18.0.4/tcp/50000/p2p/12D3KooWQwgwg4FwN1SDxXvuQkYRtuDsW7ysgHtqsZyfYv1nurQj
http
/dns/foo.com/tcp/443/https/p2p/12D3KooWQwgwg4FwN1SDxXvuQkYRtuDsW7ysgHtqsZyfYv1nurQj
https://foo.com:443
bitswap
/ip4/172.18.0.7/tcp/8888/p2p/12D3KooWBUE8A4hmnAQBJLusjYDjQ7DUTFKcqh2H2PATzCv4VLCH
/ip4/127.0.0.1/tcp/8888/p2p/12D3KooWBUE8A4hmnAQBJLusjYDjQ7DUTFKcqh2H2PATzCv4VLCH
```
Output with Private (proxy) Bitswap address:
```
libp2p
/ip4/127.0.0.1/tcp/50000/p2p/12D3KooWQwgwg4FwN1SDxXvuQkYRtuDsW7ysgHtqsZyfYv1nurQj
/ip4/172.18.0.4/tcp/50000/p2p/12D3KooWQwgwg4FwN1SDxXvuQkYRtuDsW7ysgHtqsZyfYv1nurQj
http
/dns/foo.com/tcp/443/https/p2p/12D3KooWQwgwg4FwN1SDxXvuQkYRtuDsW7 …
```
> add peerID to multiaddresses returned by boost provider retrieval-transports query

- node/config/def.go
fixes #1587 
```
./boostd config default | grep Bitswap
#BitswapPeerID = ""
#BitswapPublicAddresses = []
#BitswapPrivKeyFile = ""
```
> fix: BitswapPublicAddresses default

- gql/resolver_dealpublish.go
- gql/schema.graphql
- markets/storageadapter/dealpublisher.go
- markets/storageadapter/dealpublisher_test.go
- node/builder.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- react/src/DealPublish.js
- react/src/gql.js
Currently, Boost controls when the PSD message is sent for a deal. This decision is governed by a couple of factors.
1. A timeout value forcing to publish all deals (1 hour)
2. Maximum number of deal to be included in each message (8)
Another special case is to Publish all deals forcefully using UI button and Graphql mutation.
SPs have expressed interest in being able to control how the deal are published. The reason this control ranges from being able to control deal flow to miner to control the cost of PSD message
The new feature allows SPs to turn on manual PSD. Once this feature is turned on, Boost will no longer send any PSD messages unless explicitly prompted by the user. The feature can be turned on with the below config variable:
```
[Dealmaking]
// When set to true, the user is …
```
> feat: manual publish storage deal message

- gql/resolver_ipni.go
- gql/schema.graphql
- react/src/Ipni.js
- react/src/gql.js
This PR adds an extra row to the Provider info in Indexer page of Boost UI.
Users can compare the head to last sync ad and figure out if their sync is working or not.
> feat: show ad chain head in UI

- cmd/boostd/init.go
Fixes https://github.com/filecoin-project/boost/issues/1594
> fix: migration config bug

- node/modules/graphsync.go
- retrievalmarket/server/gsunpaidretrieval.go
Fixes https://github.com/filecoin-project/boost/issues/1602
> Fix startup with disabled index provider

- docker/devnet/boost/entrypoint.sh
- itests/framework/framework.go
- node/builder.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/dealfilter.go
- node/modules/storageminer.go
Fixes https://github.com/filecoin-project/boost/issues/1608
This PR has the following changes:
1. Update BasicDealFilter to not use cfg params as it is not required.
2. Add checks for `ExpectedSealDuration` and `MaxDealStartDelay`
3. Update `MaxDealStartDelay` to only factor in online deals. This was done keeping in mind that offline deals can take days to weeks for shipping & importing the data. We don't want them to be rejected because deal start epoch is too far away.
4. Deal Publisher should use cfg.Dealmaking.StartEpochSealingBuffer instead of cfg.LotusDealmaking.StartEpochSealingBuffer for Boost deals.
> fix: update deal filter to use `ExpectedSealDuration` and `MaxDealStartDelay`

- cmd/lib/api.go
- gql/resolver.go
- gql/resolver_maddr.go
- gql/schema.graphql
- node/modules/storageminer.go
- react/src/RetrievalLogs.css
- react/src/RetrievalLogs.js
- react/src/gql.js
Fixes https://github.com/filecoin-project/boost/issues/1621
> Show list of retrieval miners on retrievals list page

- gql/resolver.go
- gql/resolver_piece.go
- gql/schema.graphql
- node/modules/storageminer.go
- react/src/LID.js
- react/src/gql.js
Fixes https://github.com/filecoin-project/boost/issues/1619
Look up the unseal status of a deal against the multi-miner accessor, rather than just on local miner.
Also, display the miner address in the list of deals.
TODO:
Note that the miner address of the local miner (in the top left) is different from the miner address listed under LID:
> Look up unseal status against multi-miner accessor

- extern/boostd-data/client/client.go
- extern/boostd-data/ldb/db.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/svc/types/types.go
- extern/boostd-data/yugabyte/piecedoctor.go
- gql/resolver.go
- gql/resolver_lid.go
- gql/resolver_piece.go
- gql/schema.graphql
- node/modules/storageminer.go
- piecedirectory/piecedirectory.go
- react/src/LID.css
- react/src/LID.js
- react/src/gql.js
Fixes https://github.com/filecoin-project/boost/issues/1640
TODO:
> Show warning on piece doctor page if still doing initial scan

- cmd/boostd/main.go
- cmd/migrate-lid/migrate_lid.go
- extern/boostd-data/cmd/run.go
- extern/boostd-data/svc/setup_yugabyte_test_util.go
- extern/boostd-data/yugabyte/cassmigrate/20230824154306_deals_fix_maddr.go
- extern/boostd-data/yugabyte/cassmigrate/migrate.go
- extern/boostd-data/yugabyte/cassmigrate/migrate_test.go
- extern/boostd-data/yugabyte/migrations/20230824125931_use_timestamptz.sql
- extern/boostd-data/yugabyte/migrations/20230828111523_faddr.sql
- extern/boostd-data/yugabyte/migrations/migrations.go
- extern/boostd-data/yugabyte/migrator.go
- extern/boostd-data/yugabyte/service.go
- extern/boostd-data/yugabyte/setup.go
- node/modules/piecedirectory.go
Fixes https://github.com/filecoin-project/boost/issues/1646
TODO:
> Cassandra migrations

- docker/devnet/boost/entrypoint.sh
Fix an issue encountered using `sed` in the devnet with Docker Desktop for Mac.
When I tried to run devnet on my machine with Docker Desktop For Mac, I encountered an error where the boost container would shutdown while trying to run `sed` commands to update it's config, due to a permission error.
I tracked this down to https://forums.docker.com/t/sed-couldnt-open-temporary-file-xyz-permission-denied-when-using-virtiofs/125473/5 and was able to fix it by making `sed` not running inline.
Possible alternate approach: Farther down the thread there's a suggestion the problem is fixed in `sed` 4.8, but that would require updating Ubuntu to 22 in the runner.
> fix(docker): no inline `sed` commands

- go.mod
- piecedirectory/piecedirectory.go
these are required for carv2 indexes when we pass them back to a Blockstore
> fix: offsets to CAR section starts

- .github/actions/container-builder/action.yaml
- .github/workflows/container-build.yml
Build boost containers on each PR to assert that all containers used by devnet build. On non PR events publish the containers onto ghcr.io.
This should significantly reduce wait time when interacting with devnet for well known versions of boost since a user would no longer have to build all related images from scratch. The CI is setup to use GitHub actions caching layers which should further speed up builds per commit.
The containers built will have a tag prefix that corresponds to the target name of devnet dockerfile.source. This includes:
* `boost-dev`
* `booster-http-dev`
* `booster-bitswap-dev`
* `lotus-dev`
* `lotus-miner-dev`
> Build and publish boost devnet containers via CI

- .github/actions/container-builder/action.yaml
- .github/workflows/container-build.yml
Fix permissions to allow github actions to push images to ghrc.io.
Fix tag prefix for all tagging flavours to include the intermediate image name.
> Allow container build job to push images

- cmd/boost/direct_deal.go
- docker/devnet/Dockerfile.source
- extern/boostd-data/cmd/run.go
This PR will add the functionality to allow users to set termMin, termMax and expiration for allocations.
It also updated the `get-allocations` command to `list-allocations`
The default are:
TermMin = 180 days
TermMax = 5 years
Expiration = 60 days
> feat: user defined allocation policy

- cmd/boost/direct_deal.go
This PR fixes the allocation bug which caused any empty allocation request to be sent.
It also refactors the existing code:
1. New CreateAllocationMsg() function which can be reused in itests
2. printAllocations() func for reuse in existing 2 commands and any future commands
Test results:
```
boost list-allocations
AllocationID  Client  Miner  PieceCid                                                          PieceSize  TermMin  TermMax  
5             1006    1000   baga6ea4seaqpfonfro6j3gcw4uxkxbivlqn2fghx5dpulc6sbi5noz7bcvzmuiq  2048       518400   5256000  
Expiration: 172800
2             1006    1000   baga6ea4seaqpfonfro6j3gcw4uxkxbivlqn2fghx5dpulc6sbi5noz7bcvzmuiq  2048       518400   5256000  
Expiration: 172800
3             1006    1000 …
```
> fix: allocation bug, refactor func()s

- node/modules/directdeals.go
- storagemarket/direct_deals_provider.go
This PR creates a new Config struct for direct deal provider and injects the values from boost config
> feat: create DDProvider config

- cmd/boostx/boostd.go
- cmd/boostx/main.go
- cmd/boostx/sector.go
Tested on devnet
```
NAME:
boostx sector is-unsealed - boostx sector is-unsealed <Sector ID>
USAGE:
boostx sector is-unsealed [command options] [arguments...]
DESCRIPTION:
Check if a particular sector is unsealed using the miner API. This is a definitive method to check for unsealed copies
OPTIONS:
--api-fullnode value  the endpoint for the full node API
--api-storage value   the endpoint for the storage node API
--help, -h            show help
```
For pre-sealed sector
```
Sector 0 is NOT unsealed
```
For a new deal sector
```
Sector 1 is unsealed
```
> feat: add InUnsealed utility to boostx

- itests/framework/framework.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/piecedirectory.go
Tested on devnet
```
2023-09-07T16:01:53.112+0400	ERROR	fxlog	fxevent/zap.go:59	start failed	{"error": "starting local index directory client:either LocalIndexDirectory.Yugabyte{} details must be defined or LocalIndexDirectory.Leveldb must be enabled"}
Error: creating node: starting node: starting local index directory client:either LocalIndexDirectory.Yugabyte{} details must be defined or LocalIndexDirectory.Leveldb must be enabled
```
> fix: disable leveldb as LID default

- cmd/boostd/init.go
fixes #1686 
Tested on filcollins
```
#
ConfigVersion = 5
#
SealerApiInfo = "<token>:/ip4/10.2.2.22/tcp/2345/http"
#
SectorIndexApiInfo = "<token>:/ip4/10.2.2.22/tcp/2345/http"
[API]
#
#ListenAddress = "/ip4/127.0.0.1/tcp/1288/http"
#RemoteListenAddress = ""
#Timeout = "30s"
```
Start up is processing the commented config correctly.
```
2023-09-11T09:53:30.594-0400	INFO	fxlog	fxevent/zap.go:51	OnStop hook executed	{"callee": "github.com/filecoin-project/lotus/node/modules.OpenFilesystemJournal.func1()", "caller": "github.com/filecoin-project/lotus/node/modules.OpenFilesystemJournal", "runtime": "17.746µs"}
2023-09-11T09:53:30.594-0400	INFO	fxlog	fxevent/zap.go:51	OnStop hook executing	{"callee": "github.com/filecoin-project/lotus/node/modules.LockedRepo.func1.1()", "caller": …
```
> fix: init with commented config

- cmd/migrate-lid/migrate_lid.go
Tested on filcollins:
```
./migrate-lid --boost-repo ~/boost-test-migrate --vv leveldb --parallel 10 dagstore
Setting up connection and creating data structures... this might take a minute...
Migrating to leveldb Local Index Directory. See detailed logs of the migration at
migrate-leveldb.log
Migrating indices...   0% [                                                                                                                                                                                                                                                                                                                               ] (0/468) [0s:0s]2023-09-11T07:26:32.598-0400	DEBUG	migrate	migrate-lid/migrate_lid.go:385	ReadIndex	{"took": "2.184337ms"}
2023-09-11T07:26:32.598-0400	DEBUG …
```
> fix: add parallelisation to migrate-lid and improve logging

- node/modules/directdeals.go
- storagemarket/deal_execution.go
- storagemarket/direct_deals_provider.go
- storagemarket/provider.go
Once the deal has been handed off to the sealing subsystem, watch the sealing state until it reaches a final state, then mark the deal as completed.
> Watch sealing state until finalized

- cmd/boostd/recover.go
Fixes #1693 
This PR uses UnsealSectorAt() to get a reader and directly feeds the reader to the commP writer. This is the same mechanism as getting a full piece from `booster-HTTP` and calculating commP on it.
> fix: update recovery for non-car files

- .github/workflows/container-build.yml
- Makefile
- README.md
this PR makes the following changes:
1. It updates the docker devnet build to use images shipped by https://github.com/filecoin-shipyard/lotus-containers instead of docker.io/filecoin/lotus-all-in-one
2. Removes the lotus and lotus-miner images built by Boost github action.
3. Update github action to build images for amd64 and arm64.
> feat: update docker devnet build

- piecedirectory/piecedirectory.go
Fixes https://github.com/filecoin-project/lotus/issues/10935
> fix: close piece reader after generating indexes

- docker/devnet/boost/entrypoint.sh
Update the `entrypoint.sh` script to ensure Graphql and libp2p listen address are set correctly
```
root@a0bd633a88f7:/app# cat /var/lib/boost/config.toml | grep Listen
ListenAddress = "/dns/boost/tcp/1288/http"
#RemoteListenAddress = ""
ListenAddresses = ["/ip4/0.0.0.0/tcp/50000", "/ip6/::/tcp/0"]
ListenAddress = "0.0.0.0"
```
> fix: docker devnet entrypoint

- gql/resolver_sector.go
- gql/schema.graphql
- react/src/Deals.css
- react/src/Deals.js
- react/src/gql.js
As part of the work to accept deal data that is not a car file, we need to signal to the user if indexing the deal failed (because it's not a car file) in a way that
- shows the sealing status of the deal data, even if the deal failed to index
- shows buttons the SP can use to retry if necessary (or cancel)
- if the SP is not expecting car files, and therefore doesn't care about indexing, the UI signal is subtle enough that it's not disruptive or annoying
https://github.com/filecoin-project/boost/assets/169124/e87c35d5-a715-455b-bbff-4b690a79e7c4
> Show both sealing and index / announce status, if there's an error announcing

- retrievalmarket/server/validation.go
Fixes a panic caused by nil pieceCID in Graphsync query validation.
```
2023-09-23T12:12:00.968Z        INFO    modules modules/storageminer_idxprov.go:149     Started index provider engine
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b6ed78]
goroutine 310 [running]:
[github.com/filecoin-project/boost/retrievalmarket/server.(*requestValidator).getPiece(0xc001d0b270](http://github.com/filecoin-project/boost/retrievalmarket/server.(*requestValidator).getPiece(0xc001d0b270), {{0xc01a45fce0?, 0xc0227e4b00?}}, 0x0)
/home/andr/boost/retrievalmarket/server/validation.go:174 +0x218
[github.com/filecoin-project/boost/retrievalmarket/server.(*requestValidator).acceptDeal(0xc001d0b270](http://github.com/filecoi …
```
> fix: GS query panic

- react/src/DealDetail.js
Fixes
https://github.com/filecoin-project/boost/issues/1715 and remove the link from Label field
> fix: Rename deal data root cid in Boost UI

- docker/devnet/boost/entrypoint.sh
- docker/devnet/docker-compose.yaml
- gql/resolver_piece.go
- gql/schema.graphql
- react/src/App.js
- react/src/Ipni.js
- react/src/LID.css
- react/src/LID.js
- react/src/gql.js
Fixes https://github.com/filecoin-project/boost/issues/1717
This PR handles the following:
1. Create a new GQL resolver to get list of all payload CIDs for a piece CID
2. Display the above list in UI
3. Fixes the error return for payload CIDs and index entries
4. Fixes a small bug in devnet script to allow LID to retain data across restarts
5. Removed RC container in docker devnet as the image used is not suitable for MacOS.
> feat: show payload CIDs in UI

- transport/httptransport/http_transport.go
- transport/httptransport/http_transport_test.go
* Add control file that captures the number of chunks that a transfer has been started with to ensure that it stays the same across restarts.
* Control file is a set of key-value pairs separated by a newline (`\n`) character. Such format is used to ensure future extensibility without having to implement any migration logic.
> Add control file

- api/types.go
- cmd/boostci/main.go
- protocolproxy/protocolproxy.go
Address static check issues:
* remove redundant import
* lower case error string
* Use `fmt.Sprintf` to construct string value instead of `fmt.Errorf.Error()`
> Fix static check issues

- docker/devnet/boost/entrypoint.sh
- extern/boostd-data/cmd/main.go
- extern/boostd-data/ldb/db.go
- extern/boostd-data/yugabyte/piecedoctor.go
- react/src/LID.js
Fixed division by zero at two places, which can happen if Boost is installed on a new SP that has 0 deals.
Also small fix for debug level logging from boostd-data service.
We probably need an RC, such as Boost v2.1.1 after this is merged, @LexLuthr, WDYT?
TODO:
> fix LID web UI

- docker/devnet/Dockerfile.source
- docker/devnet/boost/entrypoint.sh
- docker/devnet/docker-compose.yaml
At the moment it is confusing that we are re-using the boostd repo for boostd-data, so this PR is changing this, in order to be explicit we are actually running a different process in the devnet.
> use explicit repo location for boostd-data

- docker/devnet/boost/entrypoint.sh
- storagemarket/provider.go
- storagemarket/provider_loop.go
Fixes https://github.com/filecoin-project/boost/issues/1733
This PR moves processesOnlineDeals and processOfflineDeals to their own goroutines.
Possible side effects:
1. Multiple CMD execution of custom filters in parallel (High CPU utilisation depending on the number of deal being processed)
2. The deal rejection will not be in order anymore. Say, we get deal A first and deal B later and start processing them. It is possible for deal A to be rejected for lack of resources and deal B to be accepted depending upon which goroutine finishes first. 
DO NOT MERGE
> feat: run deal filters in parallel

- react/src/Ipni.js
Without the fix
with the fix
Once the data is populated
This PR also removes the retrieval count from indexer menu item
> fix: empty IPNI UI due to lack if latest Ad CID

- extern/boostd-data/go.mod
- extern/boostd-data/go.sum
- extern/boostd-data/yugabyte/cassmigrate/20230913144459_deals_add_is_direct.go
- go.mod
- go.sum
Fixes https://github.com/filecoin-project/boost/issues/1754
> fix: handle isexist error for IsDirectDeal column in migration

- .github/ISSUE_TEMPLATE/support-ticket.yml
If the template looks good, please feel free to merge it
> Create support ticket template

- extern/boostd-data/cmd/run.go
- extern/boostd-data/svc/setup_yugabyte_test_util.go
- extern/boostd-data/yugabyte/migrator.go
- extern/boostd-data/yugabyte/service.go
- extern/boostd-data/yugabyte/setup.go
The default timeout was 6 seconds. It has been updated to 60 seconds. User can modify this with the below flag.
--CQLTimeout value               client timeout value in seconds for CQL queries (default: 60)
> feat: add cql timeout to boostd-data command

- markets/storageadapter/dealpublisher.go
- markets/storageadapter/dealpublisher_test.go
With multiminer support a single batch can include deals from different providers. An onchain message must contain deals from the same provider only. Group deals by provider and publish separate messages to satisfy this requirement.
> Group deals by provider when publish

- extern/boostd-data/yugabyte/service.go
- speed up ydb indexing by executing inserts in batches instead of concurrently
- add insert batch size database setting that is default to 10k
Car file used: `{"piececid": "bafykbzacedrrhwwbp7bcbvekiqzlzvbi65wy2ku6xkejlewz6bciasnnqycd4", "recs": 2232145}`
- The current implementation
```2023-11-01T13:06:20.289Z	WARN	boostd-data	cmd/run.go:339	added index to yugabytedb successfully	{"took": 244.186086292}```
- Batch inserts 1k batch size
```2023-11-01T12:51:23.415Z	WARN	boostd-data	cmd/run.go:348	added index to yugabytedb successfully	{"took": 47.338054792}```
- Batch inserts 10k batch size
```2023-11-01T12:53:26.419Z	WARN	boostd-data	cmd/run.go:348	added index to yugabytedb successfully	{"took": 40.236502708}```
- Batch inserts 50k batch size
```2023-11-01T12:52:23.827Z	WARN	boostd-data …
```
> fix: speed up ydb insert

- extern/boostd-data/yugabyte/service.go
This PR builds on top of the work @ischasny did with batch inserts for indices.
It basically splits the `recs` slice (which can get from 0 up to 50M-100M entries), into 32 chunks that get processed in parallel.
Considering that batch size is 10k, it makes sense to have concurrent go-routines working on inserting the index.
> yugabyte/service: parallel batch inserts for car indices

- cmd/boost/wallet_cmd.go
Before
```bash
$ ./boost wallet list                                     
Address                                                                                 Balance                   Market(Avail)  Market(Locked)  Nonce  DataCap  
f1nsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               0.182258588264391056 FIL  0 FIL          0 FIL           64     X        
f1pdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               0 FIL                     0 FIL          0 FIL           0      24739011625   
f1tbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               0 FIL                     0 FIL          0 FIL           0      19310172962816   
f1wzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx …
```
> `boost wallet list` humanize display datacap

- react/src/LID.js
We should decide how we want the piece doctor to work in general and how much sense there is in having a complicated piece doctor that makes the LID store eventually consistent.
> lid ui: remove progress bar; keep `last update`

- extern/boostd-data/svc/setup_yugabyte_test_util.go
- extern/boostd-data/yugabyte/migrator.go
Fixes https://github.com/filecoin-project/boost/issues/1808
```
$ boostd-data run yugabyte --hosts 127.0.0.1 --connect-string="postgres://postgres:postgres@127.0.0.1:5433?load_balance=true&sslmode=disable" --addr 0.0.0.0:8044 
2023/11/08 03:56:47 goose: no migrations to run. current version: 20230828111523
2023-11-08T03:56:47.934-0500    INFO    boostd-data     cmd/run.go:179  Started boostd-data yugabyte service on address 0.0.0.0:8044
```
> fix: refactor connect-string for YB specific postgres parameters

- extern/boostd-data/go.mod
- extern/boostd-data/go.sum
- go.mod
- go.sum
When boost is built from source without cloning boostd-data extern folder the go module will pull the version in go.mod which used to point to a branch commit.
The changes here changes to commit to point to a commit from main, head of `v2.1.0-rc3`. This is done by executing:
`go get github.com/filecoin-project/boost/extern/boostd-data@1622d0ce2581bcaba6c1d1c6c46d2576576fa716`
Run `go mod tidy` on root and nested modules.
Fixes #1813
> Depend on commit from main for boostd-data dependency

- cmd/boostd/recover.go
- cmd/booster-bitswap/run.go
- cmd/booster-http/run.go
- extern/boostd-data/cmd/run.go
- extern/boostd-data/yugabyte/service.go
- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/piecedirectory.go
- piecedirectory/piecedirectory.go
Add two new configuration parameters:
* `AddIndexConcurrency` for `boostd` that sets the number of concurrent tasks that each add index operation can be split into;
* `insert-concurrency` for `boost-data` that sets the number of concurrent inserts that each add index operation can be split into;
> fix: parametrise add index parallelism

- node/config/def.go
- node/config/doc_gen.go
- node/config/types.go
Reverting back to 8 after fixing the the thread batch bug
> fix: set default add index concurrency to 8

- gql/resolver.go
- gql/schema.graphql
- react/src/Components.js
- react/src/DealDetail.js
- react/src/Deals.css
- react/src/Deals.js
- react/src/LegacyDealDetail.js
- react/src/LegacyDeals.js
- react/src/ProposalLogs.css
- react/src/ProposalLogs.js
- react/src/gql.js
- storagemarket/deal_execution.go
This PR makes the following changes:
1. Add a new column for on chain deal ID (Boost and Legacy deals)
2. Create a new column "Sealing Status" and create an info button with description
3. Add info button to deal Status column
4. Fix Size for offline deals (we cannot fix for existing deals but new ones should display and retain correct size)
5. The onchainDealID and epochs do not have comma anymore
> Update deal list page

- go.mod
- go.sum
- itests/dummydeal_offline_test.go
- itests/dummydeal_test.go
- itests/framework/framework.go
- itests/graphsync_identity_cid_test.go
- itests/graphsync_retrieval_test.go
- itests/multiminer_retrieval_graphsync_test.go
- markets/utils/selectors.go
- retrievalmarket/client/client.go
* Use new go-trustless-utils primitives and traversal tools for requesting and verifying test retrievals
* Simplify Framework#Retrieve and remove test logic that doesn't make sense for these kinds of retrievals
* Wait for full startup of data transfer when making a retrieval client
Some lint errors in here that can be taken care of separately.
> fix: clean up and fix retrieval framework & tests

- piecedirectory/doctor.go
In my case (140.000 updates) shaves off 1.5 seconds per call (+ the load on the daemon) -> turns a 39 hour job into seconds
> Prefetch state claims to change O(n) calls to Lotus State to O(1)

- cmd/booster-http/run.go
I kind of wish now we did `--serve-trustless` and made `--serve-cars` an alias for that. Maybe a future TODO.
> doc: fix flag info and error message for block serving

- piecedirectory/piecedirectory.go
- react/src/DealDetail.js
- react/src/Deals.js
This PRs fixes the following:
1. Deals page displaying sealing state instead of indexing error
Earlier:
Now:
2. Some react errors about nesting paragraphs 
No console errors:
> fix: UI deal error messages

- protocolproxy/forwardinghost.go
- protocolproxy/protocolproxy.go
- retrievalmarket/lp2pimpl/transports.go
- retrievalmarket/server/queryask.go
- safe/safe.go
- storagemarket/lp2pimpl/net.go
Wrap all handlers with recovers in case something goes wrong when processing requests (similarly to `contract_deals.go`)
> safe handlers

- piecedirectory/piecedirectory.go
This is a temporary workaround to handle "slice bounds out of range" errors in podsi indexing. The bug affects a minor number of deals, so recovering here will help to unblock the users.
> fix: handle panic in podsi indexing

- storagemarket/provider.go
This fix avoids failing deals on boostd restart which have been added to a sector but have not been indexed correctly.
> fix: don't fail deals that have passed AP() but are not indexed

- piecedirectory/piecedirectory.go
POSDI index error fix for spade deals
> Fixes POSDI error

- piecedirectory/piecedirectory.go
- piecedirectory/piecedirectory_test_util.go
We should avoid on-the-fly indexing as it can lead to continuous indexing attempts from HTTP and Bitswap retrievals. It is not very efficient in cases where unsealed sector is missing or IPNI is not updated correctly.
> fix: remove on-the-fly indexing

- piecedirectory/piecedirectory.go
CC: @cryptowhizzard 
DO NOT MERGE
> fix: unexpected EOF when parsing segments for PODSI deals

- Makefile
- docker/Dockerfile.yugabyte
Bump up the Lotus version, Boost version and Yugabyte version
> chore: update devnet versions

- gql/resolver_directdeals.go
- gql/schema.graphql
- react/src/DirectDeals.js
- react/src/gql.js
The DDO UI page has been updated to match the Boost deal page. Sealing and deal lifecycle have been separated.
> fix: update DDO UI

- db/directdeals.go
- gql/resolver_dealpublish.go
- gql/resolver_piece.go
- gql/resolver_sealingpipeline.go
- gql/schema.graphql
- itests/framework/framework.go
- react/src/Components.js
- react/src/DealPublish.js
- react/src/LID.js
- react/src/SealingPipeline.js
- react/src/gql.js
- storagemarket/direct_deals_provider.go
- storagemarket/provider.go
This PR does the following:
1. Adds a check to ensure that we are not processing more than 1 deal with same client and allocationID at a time. If a deal onboarding fails for some reason, SPs can reimport with same parameters but 2 should not be running in parallel. 
2. Account for DDO deals in UI 
- Sealing pipeline
- Piece doctor page deal list
- Fix DDO SQL DB method by SectorID inputs
- Create a new SQL DB method to search with pieceCID and allocationID (speed up GQL)
> fix: account for DDO in UI

- itests/framework/framework.go
- lib/pdcleaner/pdcleaner.go
- piecedirectory/piecedirectory.go
- piecedirectory/piecedirectory_test_util.go
This feature was disabled in https://github.com/filecoin-project/boost/pull/1875 due to concerns about missing sectors. With LID clean up in place, we should drop indexes for missing sectors. This should prevent unnecessary calls to Miner.
> fix: enable on-the-fly-reindexing

- cmd/boost/direct_deal.go
- cmd/boost/util/util.go
This PR fixes the Datacap used per batch and reduces the batch size to 500.
> fix: extend-claim cli DC batching

- cmd/boostd/recover.go
The process should ignore the expired sectors.
> fix: lid recovery

- cmd/boost/direct_deal.go
- cmd/boost/util/util.go
- itests/ddo_test.go
- itests/lid_cleanup_test.go
Allows using a file to allocate in CSV format. The delimiter is ","
Fixes https://github.com/filecoin-project/boost/issues/1897
```
root@03d705eacb40:/app# boost allocate --pf ./text.txt 
about to send message with the following gas costs
max fee:      0.00000000340735296 FIL (absolute maximum amount you are willing to pay to get your transaction confirmed)
gas fee cap:  0.00000000000000012 FIL
gas limit:    28394608
gas premium:  0.000000000000000035 FIL
basefee:      0.0000000000000001 FIL
Proceed? Yes [Y/y] / No [N/n], Ctrl+C (^C) to exit y
2024-04-17T10:06:31.060Z        INFO    boost   boost/direct_deal.go:280        submitted data cap allocation message[s]
2024-04-17T10:06:31.060Z        INFO    boost   boost/direct_deal.go:281        waiting for message to be included in a block …
```
> chore: refactor allocate command

- extern/boostd-data/client/client.go
- extern/boostd-data/cmd/main.go
- extern/boostd-data/ldb/service.go
- extern/boostd-data/metrics/metrics.go
- extern/boostd-data/yugabyte/piecedoctor.go
- extern/boostd-data/yugabyte/service.go
- indexprovider/wrapper.go
- lib/pdcleaner/pdcleaner.go
- node/builder.go
- piecedirectory/doctor.go
This PR fixes the following issues:
1. Fixes dropping indexes in batches
2. Add logs for when deleting deal metadata from LID
3. Account for pdcleaner in announce-all method of index-provider
4. Account for pdcleaner in piece doctor.
5. Set boostd-data RPC logging level to ERROR to reduce the noisy logs from Bitswap requests.
> fix: add debug logs for pdcleaner

- storagemarket/direct_deals_provider.go
DDO deals with TermMin longer than Sector lifetime should be rejected as they will be dropped in later stages of sealing.
> fix: reject deals longer than sector lifetime

- cmd/boostd/init.go
I'm running boost in a devent environment for demonstrating a new deal making protocol.  Running lotus in a devnet environment naturally leads to networks that are very out of sync with devnet beacon and get into this state in a racy way dependent on the time between init and running the lotus-miner.  
`boostd run` had a very helpful flag `--nosync` which allows devnets to avoid failing on this race condition. 
It would be helpful for my usecase and minimally invasive to add this flag to `boostd init` too.
> Add nosync flag to init

- extern/boostd-data/ldb/db.go
As stated in the title.
The following payload leads to a panic, but doesn't crash the server.
```
{id:1, jsonrpc:"2.0", method:"boostddata.FlaggedPiecesList", params: [{}, "0001-01-01T00:00:00Z", 0, -1]}
```
> fix: out of bounds access in `ListFlaggedPieces`

- cmd/boostd/recover.go
Fixes :
2024-05-22T10:00:57.990+0200    DEBUG   boostd/recover.go:698   successfully processed sector   {"sector": "24242", "took": "2m10.444991835s", "deals": [54737806]}
2024-05-22T10:00:57.990+0200    DEBUG   boostd/recover.go:685   processing sector       {"sector": "24245", "deals": [54737803]}
2024-05-22T10:00:57.991+0200    WARN    boostd/recover.go:714   deal present in sector, but not in market actor state, so probably expired      {"sector": "24245", "deal": 54737803, "err": "deal 54737803 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed"}
2024-05-22T10:00:57.991+0200    DEBUG   boostd/recover.go:698   successfully processed sector   {"sector": "24245", "took": "1.1293ms", "deals": [54737803]} …
> Fix panic when recovering broken sector.

- cmd/boostd/net.go
- go.mod
The `boostd net` commands were using Lotus subcommand and this caused them to open Lotus API instead of Boost.
```
On Boost v2.3.0-rc2
lexluthr@Lexs-Mac boost % ./boostd net listen                                                                                    
/ip4/127.0.0.1/tcp/9090/p2p/12D3KooWQEeMearkt4N97yznJY9sS6ReNKoWyyoCm1H5CAZbegxy
/ip4/172.18.0.7/tcp/9090/p2p/12D3KooWQEeMearkt4N97yznJY9sS6ReNKoWyyoCm1H5CAZbegxy
Boost v2.3.0-rc1
lexluthr@Lexs-Mac boost % ./boostd net listen                     
/ip4/127.0.0.1/tcp/24000/p2p/12D3KooWQcrJrLxzHncnP7mnfuwv5hCxV8iLaHZukX93n9hBckdr
/ip6/::1/tcp/50382/p2p/12D3KooWQcrJrLxzHncnP7mnfuwv5hCxV8iLaHZukX93n9hBckdr
Fixed output
lexluthr@Lexs-Mac boost % ./boostd net listen
/ip4/127.0.0.1/tcp/24000/p2p/12D3KooWQcrJrLxzHncnP7mnfuwv5hCxV8iLaHZukX …
```
> fix: boostd net commands

- cmd/migrate-lid/migrate_lid.go
- extern/boostd-data/cmd/run.go
- extern/boostd-data/yugabyte/migrator.go
- extern/boostd-data/yugabyte/service.go
- extern/boostd-data/yugabyte/setup.go
- node/config/doc_gen.go
- node/config/types.go
- node/modules/piecedirectory.go
We are useing Yugabyte with [YCQL authentication](https://docs.yugabyte.com/preview/secure/enable-authentication/authentication-ycql/) enabled via the parameter `--use_cassandra_authentication` and [YSQL authentication](https://docs.yugabyte.com/preview/secure/enable-authentication/authentication-ysql/) enabled via `--ysql_enable_auth`. 
However, `boostd-data` is unable to utilize Cassandra authentication and can only connect using YSQL authorization through the connection string. 
This PR enables users to authenticate using [Cassandra credentials](https://github.com/yugabyte/gocql?tab=readme-ov-file#authentication).
> feat(gocql): add authentication support

- node/builder.go
- node/modules/directdeals.go
- node/modules/storageminer.go
- storagemarket/provider.go
- storagemarket/smtestutil/mocks.go
- storagemarket/types/mock_types/mocks.go
- storagemarket/types/types.go
This package was used by legacy provider and was not cleaned up properly when legacy provider was removed.
> fix: remove sectorBlocks package from Boost

- cmd/boost/direct_deal.go
- cmd/boost/util/util.go
- cmd/boostx/utils_cmd.go
- cmd/lib/common.go
This PR fixes two issues with `boost allocation`:
1. When the number of entries in `--piece-file` exceeds the default batch size of 500, the `datacap` amount calculation is incorrect, leading to erroneous messages.
2. When sending multiple messages, the nonce value remains the same because the `datastore` in `SignAndPushToMpool` does not persist(is not shared), so only the first message can be successfully sent.
After:
Tested in my calibnet environment.
> fix: boost allocate commands
